// SPDX-License-Identifier: AGPL-3.0-only

package main

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/config"
	"github.com/go-git/go-git/v5/plumbing"
	githttp "github.com/go-git/go-git/v5/plumbing/transport/http"

	"github.com/lazaretemail/lazaret/rules"
	"github.com/lazaretemail/lazaret/services/engine/store"
)

// Rule feeds: cloning detection content on a schedule.
//
// go-git rather than shelling out. The runtime image would need a git binary, and
// more to the point the URL comes from an admin form — handing attacker-adjacent
// input to a subprocess is a category of bug worth not having, and go-git also
// behaves identically whatever the host has installed.

const (
	// maxFeedFiles and maxFeedBytes bound what a feed can put on disk. A repository
	// is somebody else's, and "somebody else's repository grew to 40GB" should be a
	// failed sync rather than a full disk on the mail pipeline.
	maxFeedFiles = 20000
	maxFeedBytes = 256 << 20

	feedSyncTimeout = 10 * time.Minute
)

// feedRoot is where clones live: inside the engine's state volume, beside the
// other things that must survive a container being replaced.
func feedRoot(stateDir string) string { return filepath.Join(stateDir, "feeds") }

func feedDir(stateDir, id string) string {
	// The id is generated by the store, not supplied, but joining a path from a
	// database column deserves the check anyway.
	//
	// Base alone is not enough: filepath.Base("..") is "..", so joining it walks
	// straight back out of the feed root. Anything that is not a plain directory
	// name gets a stable substitute rather than a path.
	clean := filepath.Base(filepath.Clean(id))
	if clean == "." || clean == ".." || clean == string(filepath.Separator) || clean == "" {
		clean = "invalid"
	}
	return filepath.Join(feedRoot(stateDir), clean)
}

// FeedSyncer clones rule feeds and reloads the engine when their content changes.
type FeedSyncer struct {
	store    *store.Store
	pipeline *Pipeline
	tenant   string
	stateDir string
	localDir string
	opts     *rules.Options

	// onNewRules is called with the names of rules that appeared in a reload and
	// were not in the set that was running before it.
	//
	// This is the moment new detection content exists, and it is the only moment at
	// which "what would this have caught in what we already have" has a well-defined
	// answer. Asking it on a timer instead would either re-ask it of unchanged rules
	// forever or need a record of which rule has been swept and when — a second
	// piece of state saying what the reload already knows.
	onNewRules func(context.Context, []string)

	// reloaded says a rule set has already been loaded in this process.
	//
	// Load-bearing for onNewRules. The engine starts with only its local rules
	// directory — one rule, in a normal deployment — and the first reload brings in
	// the twelve hundred from the feeds. Compared against what was running, all
	// twelve hundred look new, so every restart would sweep the entire corpus
	// against the entire rule set. A restart is not new intelligence.
	reloaded bool
}

// OnNewRules registers what to do when a reload brings in content that was not there
// before. Optional: a deployment with no corpus has nothing to sweep.
func (f *FeedSyncer) OnNewRules(fn func(context.Context, []string)) { f.onNewRules = fn }

func NewFeedSyncer(st *store.Store, p *Pipeline, tenant, stateDir, localDir string, opts *rules.Options) *FeedSyncer {
	return &FeedSyncer{store: st, pipeline: p, tenant: tenant, stateDir: stateDir, localDir: localDir, opts: opts}
}

// SyncOne fetches a feed and records what happened.
//
// Errors are recorded and returned, never fatal: a forge being down must not stop
// mail being judged against the rules already on disk.
func (f *FeedSyncer) SyncOne(ctx context.Context, feed store.RuleFeed) error {
	ctx, cancel := context.WithTimeout(ctx, feedSyncTimeout)
	defer cancel()

	dir := feedDir(f.stateDir, feed.ID)
	commit, err := cloneOrPull(ctx, dir, feed)
	if err != nil {
		_ = f.store.RecordFeedSync(ctx, f.tenant, feed.ID, "", 0, err)
		return err
	}
	if err := stripSymlinks(dir); err != nil {
		_ = f.store.RecordFeedSync(ctx, f.tenant, feed.ID, "", 0, err)
		return err
	}

	n, err := countRules(f.feedContentDir(feed))
	if err != nil {
		_ = f.store.RecordFeedSync(ctx, f.tenant, feed.ID, "", 0, err)
		return err
	}
	return f.store.RecordFeedSync(ctx, f.tenant, feed.ID, commit, n, nil)
}

// feedContentDir is the directory rules are actually loaded from, which is the
// clone plus whatever subdirectory the feed named.
func (f *FeedSyncer) feedContentDir(feed store.RuleFeed) string {
	dir := feedDir(f.stateDir, feed.ID)
	if feed.Subdir == "" {
		return dir
	}
	// A subdir out of the database must not climb out of the clone.
	sub := filepath.Clean("/" + feed.Subdir)
	return filepath.Join(dir, sub)
}

// Dirs is every directory the engine should load rules from: the local one an
// operator mounts, plus each enabled feed.
func (f *FeedSyncer) Dirs(ctx context.Context) ([]string, error) {
	feeds, err := f.store.RuleFeeds(ctx, f.tenant, false)
	if err != nil {
		return nil, err
	}
	var dirs []string
	if f.localDir != "" {
		if _, err := os.Stat(f.localDir); err == nil {
			dirs = append(dirs, f.localDir)
		}
	}
	for _, feed := range feeds {
		if !feed.Enabled {
			continue
		}
		dir := f.feedContentDir(feed)
		if _, err := os.Stat(dir); err == nil {
			dirs = append(dirs, dir)
		}
	}
	return dirs, nil
}

// Reload rebuilds the rule set from every directory and swaps it in.
//
// The new set is built completely before anything is swapped: a feed that has just
// pulled a broken rule fails here, is logged, and the engine keeps running the set
// it already had. Replacing a working rule set with a half-loaded one because a
// third party pushed a typo is not an acceptable failure mode for a mail pipeline.
func (f *FeedSyncer) Reload(ctx context.Context) (int, error) {
	dirs, err := f.Dirs(ctx)
	if err != nil {
		return 0, err
	}
	if len(dirs) == 0 {
		return 0, errors.New("no rule directories: no local rules and no enabled feed has been cloned")
	}

	var entities []*rules.Entity
	for _, dir := range dirs {
		loaded, err := rules.LoadDir(dir)
		if err != nil {
			return 0, fmt.Errorf("loading %s: %w", dir, err)
		}
		entities = append(entities, loaded...)
	}

	engine, failures := rules.New(entities, f.opts)
	for _, bad := range failures {
		log.Printf("rule feed: skipped %v", bad)
	}
	if engine.Len() == 0 {
		return 0, errors.New("the reloaded rule set is empty; keeping the one already running")
	}

	previous := f.pipeline.rules()
	before := previous.Len()
	f.pipeline.setRules(engine)
	log.Printf("rules reloaded: %d (was %d) from %d director%s",
		engine.Len(), before, len(dirs), map[bool]string{true: "y", false: "ies"}[len(dirs) == 1])

	// Compared against the set that was actually running, not against the previous
	// reload's file list. A rule whose source changed counts as new for this purpose:
	// what it would have caught yesterday is a different question from what the old
	// version would have, and that is exactly what a sweep is for.
	first := !f.reloaded
	f.reloaded = true
	if f.onNewRules != nil && !first {
		if names := appeared(previous, engine); len(names) > 0 {
			go f.onNewRules(context.WithoutCancel(ctx), names)
		}
	}
	return engine.Len(), nil
}

// appeared names the rules in next that were not in prev, or whose source changed.
//
// An empty previous engine reports nothing: every rule is new against nothing, and
// sweeping the whole corpus over the whole corpus would file a finding for every
// message any rule has ever matched. The caller additionally skips the first reload of
// a process, which is the case that actually occurs — the engine starts with its local
// rules and the feeds arrive a moment later.
func appeared(prev, next *rules.Engine) []string {
	if prev == nil || prev.Len() == 0 {
		return nil
	}
	was := make(map[string]string, prev.Len())
	for _, c := range prev.Compiled() {
		if c.Entity != nil {
			was[c.Entity.Name] = c.Entity.Source
		}
	}
	var out []string
	for _, c := range next.Compiled() {
		if c.Entity == nil {
			continue
		}
		if src, ok := was[c.Entity.Name]; !ok || src != c.Entity.Source {
			out = append(out, c.Entity.Name)
		}
	}
	return out
}

// Run syncs due feeds forever.
//
// One pass immediately, so a fresh install has content before the first message
// arrives rather than six hours later.
func (f *FeedSyncer) Run(ctx context.Context) {
	// Load what is already on disk before doing anything else.
	//
	// This was missing and it was severe: the engine loads only its local rules
	// directory at start-up, and feed content reached the rule set solely as a
	// side effect of a sync that changed the commit. A restart with an
	// already-current clone therefore dropped every feed rule — 1257 of them —
	// and the engine came up answering with one. Nothing reported it, because
	// from the engine's point of view a one-rule rule set is a valid rule set.
	if _, err := f.Reload(ctx); err != nil {
		log.Printf("rule feeds: initial load: %v", err)
	}

	f.syncDue(ctx, true)
	tick := time.NewTicker(time.Minute)
	defer tick.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-tick.C:
			f.syncDue(ctx, false)
		}
	}
}

// syncDue syncs every enabled feed whose interval has elapsed.
func (f *FeedSyncer) syncDue(ctx context.Context, first bool) {
	feeds, err := f.store.RuleFeeds(ctx, f.tenant, true)
	if err != nil {
		log.Printf("rule feeds: listing: %v", err)
		return
	}

	changed := false
	for _, feed := range feeds {
		if !feed.Enabled || !feedDue(feed, first) {
			continue
		}
		before := feed.LastCommit
		if err := f.SyncOne(ctx, feed); err != nil {
			log.Printf("rule feed %q: %v", feed.Name, err)
			continue
		}
		after, err := f.store.RuleFeed(ctx, f.tenant, feed.ID, false)
		if err == nil && after.LastCommit != before {
			log.Printf("rule feed %q: now at %s (%d rules)", feed.Name, shortCommit(after.LastCommit), after.RuleCount)
			changed = true
		}
	}

	if changed {
		if _, err := f.Reload(ctx); err != nil {
			log.Printf("rule feeds: reload after sync: %v", err)
		}
	}
}

// feedDue reports whether a feed's interval has elapsed.
//
// A feed that has never synced is always due, including one that failed: a forge
// that was down a minute ago may be up now, and the retry is one HTTP request.
func feedDue(f store.RuleFeed, first bool) bool {
	if f.LastSync == nil || f.LastCommit == "" {
		return true
	}
	if first {
		// On start-up, only pull what is actually stale. Restarting the engine
		// should not re-clone every feed.
		return time.Since(*f.LastSync) >= time.Duration(f.EverySecs)*time.Second
	}
	return time.Since(*f.LastSync) >= time.Duration(f.EverySecs)*time.Second
}

func shortCommit(c string) string {
	if len(c) > 8 {
		return c[:8]
	}
	return c
}

// cloneOrPull brings dir up to date and returns the commit it now points at.
func cloneOrPull(ctx context.Context, dir string, feed store.RuleFeed) (string, error) {
	auth := feedAuth(feed)

	repo, err := git.PlainOpen(dir)
	if errors.Is(err, git.ErrRepositoryNotExists) {
		if err := os.MkdirAll(filepath.Dir(dir), 0o750); err != nil {
			return "", err
		}
		// Depth 1: the history of somebody else's rule repository is not evidence
		// this engine needs, and a shallow clone of the Sublime corpus is a fraction
		// of the transfer.
		opts := &git.CloneOptions{URL: feed.URL, Depth: 1, SingleBranch: true, Auth: auth}
		if feed.Branch != "" {
			opts.ReferenceName = plumbing.NewBranchReferenceName(feed.Branch)
		}
		repo, err = git.PlainCloneContext(ctx, dir, false, opts)
		if err != nil {
			return "", fmt.Errorf("cloning %s: %w", feed.URL, err)
		}
		return headCommit(repo)
	}
	if err != nil {
		return "", fmt.Errorf("opening %s: %w", dir, err)
	}

	// Fetch and hard reset rather than merge. The working tree is a cache of a
	// remote, not somewhere anyone edits, so there is nothing to preserve and a
	// merge conflict here would wedge the feed permanently.
	err = repo.FetchContext(ctx, &git.FetchOptions{
		Auth:     auth,
		Depth:    1,
		Force:    true,
		RefSpecs: []config.RefSpec{"+refs/heads/*:refs/remotes/origin/*"},
	})
	if err != nil && !errors.Is(err, git.NoErrAlreadyUpToDate) {
		return "", fmt.Errorf("fetching %s: %w", feed.URL, err)
	}

	wt, err := repo.Worktree()
	if err != nil {
		return "", err
	}
	remoteRef, err := remoteHead(repo, feed.Branch)
	if err != nil {
		return "", err
	}
	if err := wt.Reset(&git.ResetOptions{Commit: remoteRef, Mode: git.HardReset}); err != nil {
		return "", fmt.Errorf("updating %s: %w", dir, err)
	}
	return remoteRef.String(), nil
}

func feedAuth(feed store.RuleFeed) *githttp.BasicAuth {
	if feed.Secret == "" {
		return nil
	}
	// Forges accept a token as the password with any non-empty username; "x-token"
	// is conventional and avoids looking like a real account.
	return &githttp.BasicAuth{Username: "x-token", Password: feed.Secret}
}

func headCommit(repo *git.Repository) (string, error) {
	ref, err := repo.Head()
	if err != nil {
		return "", err
	}
	return ref.Hash().String(), nil
}

func remoteHead(repo *git.Repository, branch string) (plumbing.Hash, error) {
	if branch != "" {
		ref, err := repo.Reference(plumbing.NewRemoteReferenceName("origin", branch), true)
		if err != nil {
			return plumbing.ZeroHash, err
		}
		return ref.Hash(), nil
	}
	// No branch named: follow whatever the remote calls its default.
	for _, name := range []string{"main", "master"} {
		if ref, err := repo.Reference(plumbing.NewRemoteReferenceName("origin", name), true); err == nil {
			return ref.Hash(), nil
		}
	}
	ref, err := repo.Head()
	if err != nil {
		return plumbing.ZeroHash, err
	}
	return ref.Hash(), nil
}

// stripSymlinks removes every symbolic link in a freshly synced feed.
//
// Git carries symlinks, and this content comes from a repository the operator does
// not control. A link named `rules/passwd.yml` pointing at /etc/passwd would be
// read by the loader as though the repository contained it. Nothing in a rule feed
// has any reason to be a link, so they are deleted rather than resolved.
func stripSymlinks(root string) error {
	var files int
	var bytes int64
	return filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.Type()&fs.ModeSymlink != 0 {
			log.Printf("rule feed: removing symlink %s", strings.TrimPrefix(path, root))
			return os.Remove(path)
		}
		if d.IsDir() {
			return nil
		}
		files++
		if info, err := d.Info(); err == nil {
			bytes += info.Size()
		}
		if files > maxFeedFiles || bytes > maxFeedBytes {
			return fmt.Errorf("feed is too large (%d files, %d bytes); refusing to load it", files, bytes)
		}
		return nil
	})
}

// countRules reports how many entities a directory yields, for the settings page.
func countRules(dir string) (int, error) {
	loaded, err := rules.LoadDir(dir)
	if err != nil {
		return 0, err
	}
	return len(loaded), nil
}
