// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by "go run ./mdm/gen"; DO NOT EDIT.
//
// Source: enrichment.openapi.json, vendored from Sublime Security's published API reference.

package mdm

import "time"

// BrandInfoConfidence enumerates the values upstream documents for this field.
//
// # Level of confidence that the correct brand (or none) was identified
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type BrandInfoConfidence string

const (
	BrandInfoConfidenceLow    BrandInfoConfidence = "low"
	BrandInfoConfidenceMedium BrandInfoConfidence = "medium"
	BrandInfoConfidenceHigh   BrandInfoConfidence = "high"
)

// BrandInfoName enumerates the values upstream documents for this field.
//
// Name of identified brand in the target page. Null if no brand was identified.
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type BrandInfoName string

const (
	BrandInfoNameABN                    BrandInfoName = "ABN"
	BrandInfoNameADP                    BrandInfoName = "ADP"
	BrandInfoNameAOL                    BrandInfoName = "AOL"
	BrandInfoNameATT                    BrandInfoName = "AT&T"
	BrandInfoNameAdobe                  BrandInfoName = "Adobe"
	BrandInfoNameAliExpress             BrandInfoName = "AliExpress"
	BrandInfoNameAmazon                 BrandInfoName = "Amazon"
	BrandInfoNameAmericanExpress        BrandInfoName = "American Express"
	BrandInfoNameApple                  BrandInfoName = "Apple"
	BrandInfoNameAuthentisign           BrandInfoName = "Authentisign"
	BrandInfoNameAwardco                BrandInfoName = "Awardco"
	BrandInfoNameBBTCorporation         BrandInfoName = "BB&T Corporation"
	BrandInfoNameBBVA                   BrandInfoName = "BBVA"
	BrandInfoNameBT                     BrandInfoName = "BT"
	BrandInfoNameBassProShop            BrandInfoName = "Bass Pro Shop"
	BrandInfoNameBankOfAmerica          BrandInfoName = "Bank of America"
	BrandInfoNameBarclays               BrandInfoName = "Barclays"
	BrandInfoNameBelastingdienst        BrandInfoName = "Belastingdienst"
	BrandInfoNameBenteler               BrandInfoName = "Benteler"
	BrandInfoNameBeyondTrust            BrandInfoName = "BeyondTrust"
	BrandInfoNameBol                    BrandInfoName = "Bol"
	BrandInfoNameBox                    BrandInfoName = "Box"
	BrandInfoNameCFA                    BrandInfoName = "CFA"
	BrandInfoNameCNA                    BrandInfoName = "CNA"
	BrandInfoNameCVS                    BrandInfoName = "CVS"
	BrandInfoNameCaixabank              BrandInfoName = "Caixabank"
	BrandInfoNameCapitalOneBank         BrandInfoName = "Capital One Bank"
	BrandInfoNameCalPoly                BrandInfoName = "CalPoly"
	BrandInfoNameCaptcha                BrandInfoName = "Captcha"
	BrandInfoNameCarta                  BrandInfoName = "Carta"
	BrandInfoNameChase                  BrandInfoName = "Chase"
	BrandInfoNameChicagoTitle           BrandInfoName = "ChicagoTitle"
	BrandInfoNameCiti                   BrandInfoName = "Citi"
	BrandInfoNameCloudflare             BrandInfoName = "Cloudflare"
	BrandInfoNameCoinbase               BrandInfoName = "Coinbase"
	BrandInfoNameCouerMining            BrandInfoName = "Couer Mining"
	BrandInfoNameCyberArk               BrandInfoName = "CyberArk"
	BrandInfoNameDHL                    BrandInfoName = "DHL"
	BrandInfoNameDKB                    BrandInfoName = "DKB"
	BrandInfoNameDPD                    BrandInfoName = "DPD"
	BrandInfoNameDayforce               BrandInfoName = "Dayforce"
	BrandInfoNameDigid                  BrandInfoName = "Digid"
	BrandInfoNameDiscord                BrandInfoName = "Discord"
	BrandInfoNameDiscover               BrandInfoName = "Discover"
	BrandInfoNameDisney                 BrandInfoName = "Disney"
	BrandInfoNameDocuSign               BrandInfoName = "DocuSign"
	BrandInfoNameDropbox                BrandInfoName = "Dropbox"
	BrandInfoNameEY                     BrandInfoName = "EY"
	BrandInfoNameEbay                   BrandInfoName = "Ebay"
	BrandInfoNameEuropol                BrandInfoName = "Europol"
	BrandInfoNameExperian               BrandInfoName = "Experian"
	BrandInfoNameFacebook               BrandInfoName = "Facebook"
	BrandInfoNameFakeAttachment         BrandInfoName = "FakeAttachment"
	BrandInfoNameFanDuel                BrandInfoName = "FanDuel"
	BrandInfoNameFedEx                  BrandInfoName = "FedEx"
	BrandInfoNameFidelityTitle          BrandInfoName = "FidelityTitle"
	BrandInfoNameFirstAm                BrandInfoName = "FirstAm"
	BrandInfoNameFuboTV                 BrandInfoName = "FuboTV"
	BrandInfoNameGLS                    BrandInfoName = "GLS"
	BrandInfoNameGM                     BrandInfoName = "GM"
	BrandInfoNameGeekSquad              BrandInfoName = "GeekSquad"
	BrandInfoNameGeminiTrust            BrandInfoName = "Gemini Trust"
	BrandInfoNameGenericCaptcha         BrandInfoName = "Generic Captcha"
	BrandInfoNameGenericWebmail         BrandInfoName = "Generic Webmail"
	BrandInfoNameGithub                 BrandInfoName = "Github"
	BrandInfoNameGmail                  BrandInfoName = "Gmail"
	BrandInfoNameGoDaddy                BrandInfoName = "GoDaddy"
	BrandInfoNameGoogle                 BrandInfoName = "Google"
	BrandInfoNameGoogleDrive            BrandInfoName = "GoogleDrive"
	BrandInfoNameGoogleVoice            BrandInfoName = "Google Voice"
	BrandInfoNameGusto                  BrandInfoName = "Gusto"
	BrandInfoNameHSBCBank               BrandInfoName = "HSBC Bank"
	BrandInfoNameHeroku                 BrandInfoName = "Heroku"
	BrandInfoNameHomeDepot              BrandInfoName = "Home Depot"
	BrandInfoNameHubSpot                BrandInfoName = "HubSpot"
	BrandInfoNameHulu                   BrandInfoName = "Hulu"
	BrandInfoNameHuntress               BrandInfoName = "Huntress"
	BrandInfoNameING                    BrandInfoName = "ING"
	BrandInfoNameIRS                    BrandInfoName = "IRS"
	BrandInfoNameIndeed                 BrandInfoName = "Indeed"
	BrandInfoNameInstagram              BrandInfoName = "Instagram"
	BrandInfoNameInviteCompany          BrandInfoName = "Invite Company"
	BrandInfoNameJFrog                  BrandInfoName = "JFrog"
	BrandInfoNameKPN                    BrandInfoName = "KPN"
	BrandInfoNameKehe                   BrandInfoName = "Kehe"
	BrandInfoNameKeyBank                BrandInfoName = "Key Bank"
	BrandInfoNameLawyersTitle           BrandInfoName = "LawyersTitle"
	BrandInfoNameLedger                 BrandInfoName = "Ledger"
	BrandInfoNameLinkedIn               BrandInfoName = "LinkedIn"
	BrandInfoNameLloyds                 BrandInfoName = "Lloyds"
	BrandInfoNameMTBank                 BrandInfoName = "M & T Bank"
	BrandInfoNameMadisonTitle           BrandInfoName = "MadisonTitle"
	BrandInfoNameMailChimp              BrandInfoName = "MailChimp"
	BrandInfoNameMailgun                BrandInfoName = "Mailgun"
	BrandInfoNameMastercard             BrandInfoName = "Mastercard"
	BrandInfoNameMcAfee                 BrandInfoName = "McAfee"
	BrandInfoNameMeta                   BrandInfoName = "Meta"
	BrandInfoNameMetaMask               BrandInfoName = "MetaMask"
	BrandInfoNameMicrosoft              BrandInfoName = "Microsoft"
	BrandInfoNameMicrosoftOffice365     BrandInfoName = "Microsoft Office365"
	BrandInfoNameMicrosoftOneDrive      BrandInfoName = "Microsoft OneDrive"
	BrandInfoNameMicrosoftOutlook       BrandInfoName = "Microsoft Outlook"
	BrandInfoNameMicrosoftSharePoint    BrandInfoName = "Microsoft SharePoint"
	BrandInfoNameMicrosoftTeams         BrandInfoName = "Microsoft Teams"
	BrandInfoNameMimecast               BrandInfoName = "Mimecast"
	BrandInfoNameNATO                   BrandInfoName = "NATO"
	BrandInfoNameNHS                    BrandInfoName = "NHS"
	BrandInfoNameNatWest                BrandInfoName = "NatWest"
	BrandInfoNameNavan                  BrandInfoName = "Navan"
	BrandInfoNameNavyFederalCreditUnion BrandInfoName = "Navy Federal Credit Union"
	BrandInfoNameNetflix                BrandInfoName = "Netflix"
	BrandInfoNameNorton                 BrandInfoName = "Norton"
	BrandInfoNameOVO                    BrandInfoName = "OVO"
	BrandInfoNameOctopus                BrandInfoName = "Octopus"
	BrandInfoNameOkta                   BrandInfoName = "Okta"
	BrandInfoNameOldRepublicTitle       BrandInfoName = "OldRepublicTitle"
	BrandInfoNameOpenAI                 BrandInfoName = "OpenAI"
	BrandInfoNamePNC                    BrandInfoName = "PNC"
	BrandInfoNamePaloAltoNetworks       BrandInfoName = "Palo Alto Networks"
	BrandInfoNamePandora                BrandInfoName = "Pandora"
	BrandInfoNamePayPal                 BrandInfoName = "PayPal"
	BrandInfoNamePostNL                 BrandInfoName = "PostNL"
	BrandInfoNamePostbank               BrandInfoName = "Postbank"
	BrandInfoNameProton                 BrandInfoName = "Proton"
	BrandInfoNamePulley                 BrandInfoName = "Pulley"
	BrandInfoNameQuicklySign            BrandInfoName = "QuicklySign"
	BrandInfoNameQuickbooks             BrandInfoName = "Quickbooks"
	BrandInfoNameRBS                    BrandInfoName = "RBS"
	BrandInfoNameRLI                    BrandInfoName = "RLI"
	BrandInfoNameRabobank               BrandInfoName = "Rabobank"
	BrandInfoNameRakuten                BrandInfoName = "Rakuten"
	BrandInfoNameRobertHalf             BrandInfoName = "Robert Half"
	BrandInfoNameRoyalMail              BrandInfoName = "RoyalMail"
	BrandInfoNameSBB                    BrandInfoName = "SBB"
	BrandInfoNameSSA                    BrandInfoName = "SSA"
	BrandInfoNameSantander              BrandInfoName = "Santander"
	BrandInfoNameSchwab                 BrandInfoName = "Schwab"
	BrandInfoNameSendGrid               BrandInfoName = "SendGrid"
	BrandInfoNameShein                  BrandInfoName = "Shein"
	BrandInfoNameSignal                 BrandInfoName = "Signal"
	BrandInfoNameSiliconValleyBank      BrandInfoName = "Silicon Valley Bank"
	BrandInfoNameSlack                  BrandInfoName = "Slack"
	BrandInfoNameSnowflake              BrandInfoName = "Snowflake"
	BrandInfoNameSparkasse              BrandInfoName = "Sparkasse"
	BrandInfoNameSpotify                BrandInfoName = "Spotify"
	BrandInfoNameSquare                 BrandInfoName = "Square"
	BrandInfoNameStewartTitle           BrandInfoName = "StewartTitle"
	BrandInfoNameStratus                BrandInfoName = "Stratus"
	BrandInfoNameStripe                 BrandInfoName = "Stripe"
	BrandInfoNameSunTrustBank           BrandInfoName = "SunTrust Bank"
	BrandInfoNameSwissPost              BrandInfoName = "Swiss Post"
	BrandInfoNameSwisscom               BrandInfoName = "Swisscom"
	BrandInfoNameTDBank                 BrandInfoName = "TD Bank"
	BrandInfoNameTarget                 BrandInfoName = "Target"
	BrandInfoNameTargobank              BrandInfoName = "Targobank"
	BrandInfoNameThreads                BrandInfoName = "Threads"
	BrandInfoNameTicorTitle             BrandInfoName = "TicorTitle"
	BrandInfoNameTidal                  BrandInfoName = "Tidal"
	BrandInfoNameTikTok                 BrandInfoName = "TikTok"
	BrandInfoNameTrezor                 BrandInfoName = "Trezor"
	BrandInfoNameTrustWallet            BrandInfoName = "TrustWallet"
	BrandInfoNameTyrell                 BrandInfoName = "Tyrell"
	BrandInfoNameUSBank                 BrandInfoName = "U.S. Bank"
	BrandInfoNameUCSB                   BrandInfoName = "UCSB"
	BrandInfoNameUPS                    BrandInfoName = "UPS"
	BrandInfoNameUSPS                   BrandInfoName = "USPS"
	BrandInfoNameVanguard               BrandInfoName = "Vanguard"
	BrandInfoNameVenmo                  BrandInfoName = "Venmo"
	BrandInfoNameVisa                   BrandInfoName = "Visa"
	BrandInfoNameVodafone               BrandInfoName = "Vodafone"
	BrandInfoNameVolksbank              BrandInfoName = "Volksbank"
	BrandInfoNameWeTransfer             BrandInfoName = "WeTransfer"
	BrandInfoNameWellsFargo             BrandInfoName = "Wells Fargo"
	BrandInfoNameWex                    BrandInfoName = "Wex"
	BrandInfoNameWhatsApp               BrandInfoName = "WhatsApp"
	BrandInfoNameWise                   BrandInfoName = "Wise"
	BrandInfoNameWorkday                BrandInfoName = "Workday"
	BrandInfoNameWoS                    BrandInfoName = "WoS"
	BrandInfoNameX                      BrandInfoName = "X"
	BrandInfoNameYahoo                  BrandInfoName = "Yahoo"
	BrandInfoNameZebra                  BrandInfoName = "Zebra"
	BrandInfoNameZelle                  BrandInfoName = "Zelle"
	BrandInfoNameZendesk                BrandInfoName = "Zendesk"
	BrandInfoNameZiggo                  BrandInfoName = "Ziggo"
	BrandInfoNameZoom                   BrandInfoName = "Zoom"
	BrandInfoNameZscaler                BrandInfoName = "Zscaler"
)

// CredPhishConfidence enumerates the values upstream documents for this field.
//
// # Level in a credential phish assessment, only set if .disposition is phishing
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type CredPhishConfidence string

const (
	CredPhishConfidenceLow    CredPhishConfidence = "low"
	CredPhishConfidenceMedium CredPhishConfidence = "medium"
	CredPhishConfidenceHigh   CredPhishConfidence = "high"
)

// CredPhishDisposition enumerates the values upstream documents for this field.
//
// # Verdict of the link, determined by various stages of analysis
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type CredPhishDisposition string

const (
	CredPhishDispositionBenign   CredPhishDisposition = "benign"
	CredPhishDispositionPhishing CredPhishDisposition = "phishing"
	CredPhishDispositionUnknown  CredPhishDisposition = "unknown"
)

// DownloadedFileFileType enumerates the values upstream documents for this field.
//
// # File type determined by looking at the magic bytes in the file
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type DownloadedFileFileType string

const (
	DownloadedFileFileTypeN3gp    DownloadedFileFileType = "3gp"
	DownloadedFileFileTypeN7z     DownloadedFileFileType = "7z"
	DownloadedFileFileTypeZ       DownloadedFileFileType = "Z"
	DownloadedFileFileTypeAac     DownloadedFileFileType = "aac"
	DownloadedFileFileTypeAiff    DownloadedFileFileType = "aiff"
	DownloadedFileFileTypeAmr     DownloadedFileFileType = "amr"
	DownloadedFileFileTypeAr      DownloadedFileFileType = "ar"
	DownloadedFileFileTypeAvi     DownloadedFileFileType = "avi"
	DownloadedFileFileTypeBmp     DownloadedFileFileType = "bmp"
	DownloadedFileFileTypeBz2     DownloadedFileFileType = "bz2"
	DownloadedFileFileTypeCab     DownloadedFileFileType = "cab"
	DownloadedFileFileTypeCr2     DownloadedFileFileType = "cr2"
	DownloadedFileFileTypeCrx     DownloadedFileFileType = "crx"
	DownloadedFileFileTypeDcm     DownloadedFileFileType = "dcm"
	DownloadedFileFileTypeDeb     DownloadedFileFileType = "deb"
	DownloadedFileFileTypeDex     DownloadedFileFileType = "dex"
	DownloadedFileFileTypeDey     DownloadedFileFileType = "dey"
	DownloadedFileFileTypeDoc     DownloadedFileFileType = "doc"
	DownloadedFileFileTypeDocx    DownloadedFileFileType = "docx"
	DownloadedFileFileTypeDwg     DownloadedFileFileType = "dwg"
	DownloadedFileFileTypeElf     DownloadedFileFileType = "elf"
	DownloadedFileFileTypeEot     DownloadedFileFileType = "eot"
	DownloadedFileFileTypeEpub    DownloadedFileFileType = "epub"
	DownloadedFileFileTypeExe     DownloadedFileFileType = "exe"
	DownloadedFileFileTypeFlac    DownloadedFileFileType = "flac"
	DownloadedFileFileTypeFlv     DownloadedFileFileType = "flv"
	DownloadedFileFileTypeGif     DownloadedFileFileType = "gif"
	DownloadedFileFileTypeGz      DownloadedFileFileType = "gz"
	DownloadedFileFileTypeHeif    DownloadedFileFileType = "heif"
	DownloadedFileFileTypeHTML    DownloadedFileFileType = "html"
	DownloadedFileFileTypeIco     DownloadedFileFileType = "ico"
	DownloadedFileFileTypeIcs     DownloadedFileFileType = "ics"
	DownloadedFileFileTypeIso     DownloadedFileFileType = "iso"
	DownloadedFileFileTypeJp2     DownloadedFileFileType = "jp2"
	DownloadedFileFileTypeJpg     DownloadedFileFileType = "jpg"
	DownloadedFileFileTypeJxr     DownloadedFileFileType = "jxr"
	DownloadedFileFileTypeLz      DownloadedFileFileType = "lz"
	DownloadedFileFileTypeM4a     DownloadedFileFileType = "m4a"
	DownloadedFileFileTypeM4v     DownloadedFileFileType = "m4v"
	DownloadedFileFileTypeMacho   DownloadedFileFileType = "macho"
	DownloadedFileFileTypeMid     DownloadedFileFileType = "mid"
	DownloadedFileFileTypeMkv     DownloadedFileFileType = "mkv"
	DownloadedFileFileTypeMov     DownloadedFileFileType = "mov"
	DownloadedFileFileTypeMp3     DownloadedFileFileType = "mp3"
	DownloadedFileFileTypeMp4     DownloadedFileFileType = "mp4"
	DownloadedFileFileTypeMpg     DownloadedFileFileType = "mpg"
	DownloadedFileFileTypeNes     DownloadedFileFileType = "nes"
	DownloadedFileFileTypeOgg     DownloadedFileFileType = "ogg"
	DownloadedFileFileTypeOtf     DownloadedFileFileType = "otf"
	DownloadedFileFileTypePdf     DownloadedFileFileType = "pdf"
	DownloadedFileFileTypePng     DownloadedFileFileType = "png"
	DownloadedFileFileTypePpt     DownloadedFileFileType = "ppt"
	DownloadedFileFileTypePptx    DownloadedFileFileType = "pptx"
	DownloadedFileFileTypePs      DownloadedFileFileType = "ps"
	DownloadedFileFileTypePsd     DownloadedFileFileType = "psd"
	DownloadedFileFileTypeRar     DownloadedFileFileType = "rar"
	DownloadedFileFileTypeRpm     DownloadedFileFileType = "rpm"
	DownloadedFileFileTypeRtf     DownloadedFileFileType = "rtf"
	DownloadedFileFileTypeSqlite  DownloadedFileFileType = "sqlite"
	DownloadedFileFileTypeSvg     DownloadedFileFileType = "svg"
	DownloadedFileFileTypeSwf     DownloadedFileFileType = "swf"
	DownloadedFileFileTypeTar     DownloadedFileFileType = "tar"
	DownloadedFileFileTypeTif     DownloadedFileFileType = "tif"
	DownloadedFileFileTypeTtf     DownloadedFileFileType = "ttf"
	DownloadedFileFileTypeWasm    DownloadedFileFileType = "wasm"
	DownloadedFileFileTypeWav     DownloadedFileFileType = "wav"
	DownloadedFileFileTypeWebm    DownloadedFileFileType = "webm"
	DownloadedFileFileTypeWebp    DownloadedFileFileType = "webp"
	DownloadedFileFileTypeWmv     DownloadedFileFileType = "wmv"
	DownloadedFileFileTypeWoff    DownloadedFileFileType = "woff"
	DownloadedFileFileTypeWoff2   DownloadedFileFileType = "woff2"
	DownloadedFileFileTypeXls     DownloadedFileFileType = "xls"
	DownloadedFileFileTypeXlsx    DownloadedFileFileType = "xlsx"
	DownloadedFileFileTypeXz      DownloadedFileFileType = "xz"
	DownloadedFileFileTypeZip     DownloadedFileFileType = "zip"
	DownloadedFileFileTypeZst     DownloadedFileFileType = "zst"
	DownloadedFileFileTypeUnknown DownloadedFileFileType = "unknown"
)

// FileFileType enumerates the values upstream documents for this field.
//
// # File type determined by looking at the magic bytes in the file
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type FileFileType string

const (
	FileFileTypeN3gp    FileFileType = "3gp"
	FileFileTypeN7z     FileFileType = "7z"
	FileFileTypeZ       FileFileType = "Z"
	FileFileTypeAac     FileFileType = "aac"
	FileFileTypeAiff    FileFileType = "aiff"
	FileFileTypeAmr     FileFileType = "amr"
	FileFileTypeAr      FileFileType = "ar"
	FileFileTypeAvi     FileFileType = "avi"
	FileFileTypeBmp     FileFileType = "bmp"
	FileFileTypeBz2     FileFileType = "bz2"
	FileFileTypeCab     FileFileType = "cab"
	FileFileTypeCr2     FileFileType = "cr2"
	FileFileTypeCrx     FileFileType = "crx"
	FileFileTypeDcm     FileFileType = "dcm"
	FileFileTypeDeb     FileFileType = "deb"
	FileFileTypeDex     FileFileType = "dex"
	FileFileTypeDey     FileFileType = "dey"
	FileFileTypeDoc     FileFileType = "doc"
	FileFileTypeDocx    FileFileType = "docx"
	FileFileTypeDwg     FileFileType = "dwg"
	FileFileTypeElf     FileFileType = "elf"
	FileFileTypeEot     FileFileType = "eot"
	FileFileTypeEpub    FileFileType = "epub"
	FileFileTypeExe     FileFileType = "exe"
	FileFileTypeFlac    FileFileType = "flac"
	FileFileTypeFlv     FileFileType = "flv"
	FileFileTypeGif     FileFileType = "gif"
	FileFileTypeGz      FileFileType = "gz"
	FileFileTypeHeif    FileFileType = "heif"
	FileFileTypeHTML    FileFileType = "html"
	FileFileTypeIco     FileFileType = "ico"
	FileFileTypeIcs     FileFileType = "ics"
	FileFileTypeIso     FileFileType = "iso"
	FileFileTypeJp2     FileFileType = "jp2"
	FileFileTypeJpg     FileFileType = "jpg"
	FileFileTypeJxr     FileFileType = "jxr"
	FileFileTypeLz      FileFileType = "lz"
	FileFileTypeM4a     FileFileType = "m4a"
	FileFileTypeM4v     FileFileType = "m4v"
	FileFileTypeMacho   FileFileType = "macho"
	FileFileTypeMid     FileFileType = "mid"
	FileFileTypeMkv     FileFileType = "mkv"
	FileFileTypeMov     FileFileType = "mov"
	FileFileTypeMp3     FileFileType = "mp3"
	FileFileTypeMp4     FileFileType = "mp4"
	FileFileTypeMpg     FileFileType = "mpg"
	FileFileTypeNes     FileFileType = "nes"
	FileFileTypeOgg     FileFileType = "ogg"
	FileFileTypeOtf     FileFileType = "otf"
	FileFileTypePdf     FileFileType = "pdf"
	FileFileTypePng     FileFileType = "png"
	FileFileTypePpt     FileFileType = "ppt"
	FileFileTypePptx    FileFileType = "pptx"
	FileFileTypePs      FileFileType = "ps"
	FileFileTypePsd     FileFileType = "psd"
	FileFileTypeRar     FileFileType = "rar"
	FileFileTypeRpm     FileFileType = "rpm"
	FileFileTypeRtf     FileFileType = "rtf"
	FileFileTypeSqlite  FileFileType = "sqlite"
	FileFileTypeSvg     FileFileType = "svg"
	FileFileTypeSwf     FileFileType = "swf"
	FileFileTypeTar     FileFileType = "tar"
	FileFileTypeTif     FileFileType = "tif"
	FileFileTypeTtf     FileFileType = "ttf"
	FileFileTypeWasm    FileFileType = "wasm"
	FileFileTypeWav     FileFileType = "wav"
	FileFileTypeWebm    FileFileType = "webm"
	FileFileTypeWebp    FileFileType = "webp"
	FileFileTypeWmv     FileFileType = "wmv"
	FileFileTypeWoff    FileFileType = "woff"
	FileFileTypeWoff2   FileFileType = "woff2"
	FileFileTypeXls     FileFileType = "xls"
	FileFileTypeXlsx    FileFileType = "xlsx"
	FileFileTypeXz      FileFileType = "xz"
	FileFileTypeZip     FileFileType = "zip"
	FileFileTypeZst     FileFileType = "zst"
	FileFileTypeUnknown FileFileType = "unknown"
)

// StrelkaFlavorsYara enumerates the values upstream documents for this field.
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type StrelkaFlavorsYara string

const (
	StrelkaFlavorsYaraN7zipFile             StrelkaFlavorsYara = "_7zip_file"
	StrelkaFlavorsYaraArjFile               StrelkaFlavorsYara = "arj_file"
	StrelkaFlavorsYaraBrowserManifest       StrelkaFlavorsYara = "browser_manifest"
	StrelkaFlavorsYaraCabFile               StrelkaFlavorsYara = "cab_file"
	StrelkaFlavorsYaraCpioFile              StrelkaFlavorsYara = "cpio_file"
	StrelkaFlavorsYaraEncryptedZip          StrelkaFlavorsYara = "encrypted_zip"
	StrelkaFlavorsYaraEncryptedWordDocument StrelkaFlavorsYara = "encrypted_word_document"
	StrelkaFlavorsYaraPdfEncryptionDict     StrelkaFlavorsYara = "pdf_encryption_dict"
	StrelkaFlavorsYaraIsoFile               StrelkaFlavorsYara = "iso_file"
	StrelkaFlavorsYaraMhtmlFile             StrelkaFlavorsYara = "mhtml_file"
	StrelkaFlavorsYaraRarFile               StrelkaFlavorsYara = "rar_file"
	StrelkaFlavorsYaraTarFile               StrelkaFlavorsYara = "tar_file"
	StrelkaFlavorsYaraXarFile               StrelkaFlavorsYara = "xar_file"
	StrelkaFlavorsYaraZipFile               StrelkaFlavorsYara = "zip_file"
	StrelkaFlavorsYaraMp3File               StrelkaFlavorsYara = "mp3_file"
	StrelkaFlavorsYaraPkcs7File             StrelkaFlavorsYara = "pkcs7_file"
	StrelkaFlavorsYaraX509DerFile           StrelkaFlavorsYara = "x509_der_file"
	StrelkaFlavorsYaraX509PemFile           StrelkaFlavorsYara = "x509_pem_file"
	StrelkaFlavorsYaraBzip2File             StrelkaFlavorsYara = "bzip2_file"
	StrelkaFlavorsYaraGzipFile              StrelkaFlavorsYara = "gzip_file"
	StrelkaFlavorsYaraLzmaFile              StrelkaFlavorsYara = "lzma_file"
	StrelkaFlavorsYaraXzFile                StrelkaFlavorsYara = "xz_file"
	StrelkaFlavorsYaraZlibFile              StrelkaFlavorsYara = "zlib_file"
	StrelkaFlavorsYaraDocSubheaderFile      StrelkaFlavorsYara = "doc_subheader_file"
	StrelkaFlavorsYaraMsoFile               StrelkaFlavorsYara = "mso_file"
	StrelkaFlavorsYaraOlecfFile             StrelkaFlavorsYara = "olecf_file"
	StrelkaFlavorsYaraOoxmlFile             StrelkaFlavorsYara = "ooxml_file"
	StrelkaFlavorsYaraPdfFile               StrelkaFlavorsYara = "pdf_file"
	StrelkaFlavorsYaraPoiHpbfFile           StrelkaFlavorsYara = "poi_hpbf_file"
	StrelkaFlavorsYaraRtfFile               StrelkaFlavorsYara = "rtf_file"
	StrelkaFlavorsYaraVbframeFile           StrelkaFlavorsYara = "vbframe_file"
	StrelkaFlavorsYaraWordmlFile            StrelkaFlavorsYara = "wordml_file"
	StrelkaFlavorsYaraXfdfFile              StrelkaFlavorsYara = "xfdf_file"
	StrelkaFlavorsYaraEmailFile             StrelkaFlavorsYara = "email_file"
	StrelkaFlavorsYaraTnefFile              StrelkaFlavorsYara = "tnef_file"
	StrelkaFlavorsYaraBase64Pe              StrelkaFlavorsYara = "base64_pe"
	StrelkaFlavorsYaraPgpFile               StrelkaFlavorsYara = "pgp_file"
	StrelkaFlavorsYaraElfFile               StrelkaFlavorsYara = "elf_file"
	StrelkaFlavorsYaraLnkFile               StrelkaFlavorsYara = "lnk_file"
	StrelkaFlavorsYaraMachoFile             StrelkaFlavorsYara = "macho_file"
	StrelkaFlavorsYaraMzFile                StrelkaFlavorsYara = "mz_file"
	StrelkaFlavorsYaraBmpFile               StrelkaFlavorsYara = "bmp_file"
	StrelkaFlavorsYaraCmapFile              StrelkaFlavorsYara = "cmap_file"
	StrelkaFlavorsYaraGifFile               StrelkaFlavorsYara = "gif_file"
	StrelkaFlavorsYaraJpegFile              StrelkaFlavorsYara = "jpeg_file"
	StrelkaFlavorsYaraPostscriptFile        StrelkaFlavorsYara = "postscript_file"
	StrelkaFlavorsYaraPngFile               StrelkaFlavorsYara = "png_file"
	StrelkaFlavorsYaraPsdFile               StrelkaFlavorsYara = "psd_file"
	StrelkaFlavorsYaraPsdImageFile          StrelkaFlavorsYara = "psd_image_file"
	StrelkaFlavorsYaraSvgFile               StrelkaFlavorsYara = "svg_file"
	StrelkaFlavorsYaraXiccFile              StrelkaFlavorsYara = "xicc_file"
	StrelkaFlavorsYaraXmpFile               StrelkaFlavorsYara = "xmp_file"
	StrelkaFlavorsYaraJarManifestFile       StrelkaFlavorsYara = "jar_manifest_file"
	StrelkaFlavorsYaraBplistFile            StrelkaFlavorsYara = "bplist_file"
	StrelkaFlavorsYaraFwsFile               StrelkaFlavorsYara = "fws_file"
	StrelkaFlavorsYaraCwsFile               StrelkaFlavorsYara = "cws_file"
	StrelkaFlavorsYaraZwsFile               StrelkaFlavorsYara = "zws_file"
	StrelkaFlavorsYaraDebianPackageFile     StrelkaFlavorsYara = "debian_package_file"
	StrelkaFlavorsYaraRpmFile               StrelkaFlavorsYara = "rpm_file"
	StrelkaFlavorsYaraUpxFile               StrelkaFlavorsYara = "upx_file"
	StrelkaFlavorsYaraBatchFile             StrelkaFlavorsYara = "batch_file"
	StrelkaFlavorsYaraJavascriptFile        StrelkaFlavorsYara = "javascript_file"
	StrelkaFlavorsYaraVbFile                StrelkaFlavorsYara = "vb_file"
	StrelkaFlavorsYaraHtaFile               StrelkaFlavorsYara = "hta_file"
	StrelkaFlavorsYaraHTMLFile              StrelkaFlavorsYara = "html_file"
	StrelkaFlavorsYaraIniFile               StrelkaFlavorsYara = "ini_file"
	StrelkaFlavorsYaraJSONFile              StrelkaFlavorsYara = "json_file"
	StrelkaFlavorsYaraPhpFile               StrelkaFlavorsYara = "php_file"
	StrelkaFlavorsYaraPlistFile             StrelkaFlavorsYara = "plist_file"
	StrelkaFlavorsYaraSoapFile              StrelkaFlavorsYara = "soap_file"
	StrelkaFlavorsYaraXmlFile               StrelkaFlavorsYara = "xml_file"
	StrelkaFlavorsYaraAviFile               StrelkaFlavorsYara = "avi_file"
	StrelkaFlavorsYaraWmvFile               StrelkaFlavorsYara = "wmv_file"
)

// StrelkaICSAttachmentType enumerates the values upstream documents for this field.
//
// # Attachment type
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type StrelkaICSAttachmentType string

const (
	StrelkaICSAttachmentTypeBinary       StrelkaICSAttachmentType = "binary"
	StrelkaICSAttachmentTypeBase64Binary StrelkaICSAttachmentType = "base64_binary"
	StrelkaICSAttachmentTypeURI          StrelkaICSAttachmentType = "uri"
	StrelkaICSAttachmentTypeOther        StrelkaICSAttachmentType = "other"
)

// StrelkaICSComponentType enumerates the values upstream documents for this field.
//
// # Component type
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type StrelkaICSComponentType string

const (
	StrelkaICSComponentTypeVEVENT    StrelkaICSComponentType = "VEVENT"
	StrelkaICSComponentTypeVTODO     StrelkaICSComponentType = "VTODO"
	StrelkaICSComponentTypeVJOURNAL  StrelkaICSComponentType = "VJOURNAL"
	StrelkaICSComponentTypeVTIMEZONE StrelkaICSComponentType = "VTIMEZONE"
	StrelkaICSComponentTypeVALARM    StrelkaICSComponentType = "VALARM"
)

// StrelkaQRType enumerates the values upstream documents for this field.
//
// # Type of content, if known
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type StrelkaQRType string

const (
	StrelkaQRTypeEmail     StrelkaQRType = "email"
	StrelkaQRTypeMobile    StrelkaQRType = "mobile"
	StrelkaQRTypeApp       StrelkaQRType = "app"
	StrelkaQRTypeGeo       StrelkaQRType = "geo"
	StrelkaQRTypeWifi      StrelkaQRType = "wifi"
	StrelkaQRTypeURL       StrelkaQRType = "url"
	StrelkaQRTypeUndefined StrelkaQRType = "undefined"
)

// BrandInfo information about the recognized brand on the target page
type BrandInfo struct {

	// Level of confidence that the correct brand (or none) was identified
	Confidence *BrandInfoConfidence `json:"confidence,omitempty"`

	// Name of identified brand in the target page. Null if no brand was identified.
	Name *BrandInfoName `json:"name,omitempty"`
}

// CredPhish credPhish analysis of the screenshot taken for the final URL
type CredPhish struct {
	Brand *BrandInfo `json:"brand,omitempty"`

	// Level in a credential phish assessment, only set if .disposition is phishing
	Confidence *CredPhishConfidence `json:"confidence,omitempty"`

	// Final page contains a captcha test
	ContainsCaptcha *bool `json:"contains_captcha,omitempty"`

	// Final page resembles a login screen
	ContainsLogin *bool `json:"contains_login,omitempty"`

	// Verdict of the link, determined by various stages of analysis
	Disposition *CredPhishDisposition `json:"disposition,omitempty"`
}

// LinkAnalysisRunDiagnostics INTERNAL
type LinkAnalysisRunDiagnostics struct {

	// When the diagnostic object was created
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// ID of the customer link exclusion that caused the skip
	MatchedExclusionRuleID *string `json:"matched_exclusion_rule_id,omitempty"`

	// Reason the URL was [not] submitted to Link Analysis
	SubmitVerdict *string `json:"submit_verdict,omitempty"`

	// The URL upon which the submit verdict was based
	SubmitVerdictURL *string `json:"submit_verdict_url,omitempty"`
}

// JSONValue response from the URL decoded as a JSON object for application/json content types
type JSONValue struct {
}

// LinkAnalysisOutput is the Handler_typesLinkAnalysisResponse component of the Message Data Model.
type LinkAnalysisOutput struct {

	// Additional HTTP responses for the page, which could be additional resources, XHR
	// requests, etc.
	AdditionalResponses []*AdditionalResponse `json:"additional_responses,omitempty"`

	// Whether the target page was successfully analyzed for credential phishing attempts
	Analyzed *bool `json:"analyzed,omitempty"`

	// Content type of the page
	ContentType  *string                     `json:"content_type,omitempty"`
	Credphish    *CredPhish                  `json:"credphish,omitempty"`
	Diagnostics  *LinkAnalysisRunDiagnostics `json:"diagnostics,omitempty"`
	EffectiveURL *URL                        `json:"effective_url,omitempty"`

	// All downloads from the page. These must download without interaction and within a few
	// seconds
	FilesDownloaded []*DownloadedFile `json:"files_downloaded,omitempty"`
	FinalDom        *FinalDOM         `json:"final_dom,omitempty"`
	OriginalURL     *URL              `json:"original_url,omitempty"`

	// HTTP status code of the page
	PageStatusCode *int64 `json:"page_status_code,omitempty"`

	// Each URL which the link analysis service was redirected through
	RedirectHistory []*URL `json:"redirect_history,omitempty"`

	// Whether the page was successfully retrieved
	Retrieved *bool `json:"retrieved,omitempty"`

	// Time the page was retrieved
	RetrievedAt *time.Time `json:"retrieved_at,omitempty"`
	Screenshot  *File      `json:"screenshot,omitempty"`

	// HTTP status code for the requested page
	StatusCode *int64 `json:"status_code,omitempty"`

	// Whether the page was submitted to be retrieved for analysis
	Submitted *bool `json:"submitted,omitempty"`

	// Detection tags emitted by the URL scanner
	Tags []string `json:"tags,omitempty"`

	// All unique URLs accessed during the analysis
	UniqueURLsAccessed []*URL `json:"unique_urls_accessed,omitempty"`

	// Whether the link would have been analyzed if run in a rule
	WouldAnalyze *bool `json:"would_analyze,omitempty"`

	// Whether the link would have been submitted if run in a rule
	WouldSubmit *bool `json:"would_submit,omitempty"`
}

// AdditionalResponse is the Link_analysis_typesAdditionalResponse component of the Message Data Model.
type AdditionalResponse struct {

	// Content type of the response
	ContentType *string         `json:"content_type,omitempty"`
	File        *DownloadedFile `json:"file,omitempty"`
	JSON        *JSONValue      `json:"json,omitempty"`

	// HTTP status code for the response
	StatusCode *int64 `json:"status_code,omitempty"`
	URL        *URL   `json:"url,omitempty"`
}

// DownloadedFile raw HTTP response payload as a file
type DownloadedFile struct {

	// File extension from context such as headers
	FileExtension *string `json:"file_extension,omitempty"`

	// File name
	FileName *string `json:"file_name,omitempty"`

	// File type determined by looking at the magic bytes in the file
	FileType *DownloadedFileFileType `json:"file_type,omitempty"`

	// MD5 hash of the downloaded file
	MD5 *string `json:"md5,omitempty"`

	// Base64 encoded source of the file
	Raw []byte `json:"raw,omitempty"`

	// SHA1 hash of the downloaded file
	SHA1 *string `json:"sha1,omitempty"`

	// SHA256 hash of the downloaded file
	SHA256 *string `json:"sha256,omitempty"`

	// Size of the file in bytes
	Size *int64 `json:"size,omitempty"`
}

// FinalDOM full DOM of the analyzed URL
type FinalDOM struct {

	// Visible text of the HTML document, with invisible characters removed and non-ASCII
	// characters converted to ASCII spaces.
	DisplayText *string `json:"display_text,omitempty"`

	// Inner text of the HTML document that doesn't include HTML tags.
	InnerText *string `json:"inner_text,omitempty"`

	// All links found in the HTML document
	Links []*Link `json:"links,omitempty"`

	// Decoded raw content of a body text type (text/[subtype] section)
	Raw *string `json:"raw,omitempty"`
}

// File file containing screenshot of final_url
type File struct {

	// File extension from context such as headers
	FileExtension *string `json:"file_extension,omitempty"`

	// File name
	FileName *string `json:"file_name,omitempty"`

	// File type determined by looking at the magic bytes in the file
	FileType *FileFileType `json:"file_type,omitempty"`

	// Base64 encoded source of the file
	Raw []byte `json:"raw,omitempty"`

	// Size of the file in bytes
	Size *int64 `json:"size,omitempty"`
}

// StrelkaBZip2 unpacks bzip2 files. Reports size
type StrelkaBZip2 struct {

	// Size of uncompressed file within.
	Size *int64 `json:"size,omitempty"`
}

// StrelkaDocX extracts details for a document, and explodes the text for further scanning.
type StrelkaDocX struct {
	Author   *string    `json:"author,omitempty"`
	Category *string    `json:"category,omitempty"`
	Comments *string    `json:"comments,omitempty"`
	Created  *time.Time `json:"created,omitempty"`

	// all non black (#000000) detected font colors. represented as web colors (hex) without
	// '#' prefix.
	FontColors  []string   `json:"font_colors,omitempty"`
	ImageCount  *int64     `json:"image_count,omitempty"`
	Keywords    *string    `json:"keywords,omitempty"`
	LastPrinted *time.Time `json:"last_printed,omitempty"`
	Modified    *time.Time `json:"modified,omitempty"`
	Revision    *int64     `json:"revision,omitempty"`
	Subject     *string    `json:"subject,omitempty"`
	Title       *string    `json:"title,omitempty"`
	WordCount   *int64     `json:"word_count,omitempty"`
}

// StrelkaEmbeddedHTMLScript is the StrelkaEmbeddedHTMLScript component of the Message Data Model.
type StrelkaEmbeddedHTMLScript struct {

	// Language of script, e.g. 'javascript'
	Language *string `json:"language,omitempty"`
	Scripts  *string `json:"scripts,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// StrelkaEncryptedDoc unpacks encrypted doc files by trying to break the password. Does not report totals
type StrelkaEncryptedDoc struct {

	// If the doc was successfully opened, this is the password for the doc.
	CrackedPassword *string `json:"cracked_password,omitempty"`
}

// StrelkaEncryptedPdf unpacks encrypted PDF files by trying to break the password.
type StrelkaEncryptedPdf struct {

	// If the PDF was successfully opened, this is the password for the PDF.
	CrackedPassword *string `json:"cracked_password,omitempty"`
}

// StrelkaEncryptedZip unpacks encrypted ZIP files by trying to break the password. Reports total files even
// if the zip could not be cracked.
type StrelkaEncryptedZip struct {

	// If the ZIP was successfully opened, this is the password for the zip.
	CrackedPassword *string `json:"cracked_password,omitempty"`
	TotalExtracted  *int64  `json:"total_extracted,omitempty"`
	TotalFiles      *int64  `json:"total_files,omitempty"`
}

// StrelkaEntropy shannon entropy of file
type StrelkaEntropy struct {

	// Shannon entropy (log base 2). A higher number means higher entropy.
	Entropy *float64 `json:"entropy,omitempty"`
}

// StrelkaExifTool responses from the popular ExifTools application
type StrelkaExifTool struct {
	CommandLineArguments *string          `json:"command_line_arguments,omitempty"`
	CreateDate           *time.Time       `json:"create_date,omitempty"`
	Creator              *string          `json:"creator,omitempty"`
	ExifToolVersion      *float64         `json:"exif_tool_version,omitempty"`
	Fields               []*StrelkaKeyVal `json:"fields,omitempty"`
	FilePermissions      *string          `json:"file_permissions,omitempty"`
	FileType             *string          `json:"file_type,omitempty"`
	FileTypeExtension    *string          `json:"file_type_extension,omitempty"`
	Flags                []string         `json:"flags,omitempty"`
	HotKey               *string          `json:"hot_key,omitempty"`

	// In pixels
	ImageHeight *int64 `json:"image_height,omitempty"`

	// In pixels
	ImageWidth          *int64     `json:"image_width,omitempty"`
	Linearized          *string    `json:"linearized,omitempty"`
	LocalBasePath       *string    `json:"local_base_path,omitempty"`
	ModifyDate          *time.Time `json:"modify_date,omitempty"`
	PageCount           *int64     `json:"page_count,omitempty"`
	PdfVersion          *string    `json:"pdf_version,omitempty"`
	Producer            *string    `json:"producer,omitempty"`
	RelativePath        *string    `json:"relative_path,omitempty"`
	RunWindow           *string    `json:"run_window,omitempty"`
	SourceFile          *string    `json:"source_file,omitempty"`
	TargetFileDosName   *string    `json:"target_file_dos_name,omitempty"`
	Title               *string    `json:"title,omitempty"`
	ZipBitFlag          *int64     `json:"zip_bit_flag,omitempty"`
	ZipCompressedSize   *int64     `json:"zip_compressed_size,omitempty"`
	ZipFileName         *string    `json:"zip_file_name,omitempty"`
	ZipModifyDate       *time.Time `json:"zip_modify_date,omitempty"`
	ZipUncompressedSize *int64     `json:"zip_uncompressed_size,omitempty"`
}

// StrelkaFlavors matched yara and mime for file type identification
type StrelkaFlavors struct {

	// Flavors marked by scanners exploding a file
	External []string `json:"external,omitempty"`

	// Detected MIME type using the libmagic unix utility.
	MIME *string `json:"mime,omitempty"`

	// Matched YARA rules, for current definitions see
	// [here](https://github.com/sublime-security/strelka/blob/main/build/configs/taste.yara)
	Yara []StrelkaFlavorsYara `json:"yara,omitempty"`
}

// StrelkaGZip unpacks gzip. Reports the size
type StrelkaGZip struct {

	// Size of uncompressed file within.
	Size *int64 `json:"size,omitempty"`
}

// StrelkaHTML scripts and basic details from HTML files. Explodes scripts for further scanning.
type StrelkaHTML struct {
	Hyperlinks []string `json:"hyperlinks,omitempty"`

	// All unique identifiers present in JS. unescape and write may be considered suspicious;
	// a variable name is also an identifier.
	Scripts []*StrelkaEmbeddedHTMLScript `json:"scripts,omitempty"`

	// HTML Span Tags
	Spans          []*StrelkaHTMLSpan `json:"spans,omitempty"`
	Title          *string            `json:"title,omitempty"`
	TotalExtracted *int64             `json:"total_extracted,omitempty"`
}

// StrelkaHTMLSpan is the StrelkaHTMLSpan component of the Message Data Model.
type StrelkaHTMLSpan struct {
	Style *string `json:"style,omitempty"`
}

// StrelkaHash multiple hash algorithms
type StrelkaHash struct {
	MD5    *string `json:"md5,omitempty"`
	SHA1   *string `json:"sha1,omitempty"`
	SHA256 *string `json:"sha256,omitempty"`
	Ssdeep *string `json:"ssdeep,omitempty"`
}

// StrelkaICS parses iCalendar files and extracts events, attachments, and metadata
type StrelkaICS struct {

	// Parsed calendar objects
	Calendars []*StrelkaICSCalendar `json:"calendars,omitempty"`

	// Warning/error flags from parsing
	Flags []string `json:"flags,omitempty"`

	// Error message if parsing failed
	ParseError     *string          `json:"parse_error,omitempty"`
	Total          *StrelkaICSTotal `json:"total,omitempty"`
	TotalExtracted *int64           `json:"total_extracted,omitempty"`
	TotalFiles     *int64           `json:"total_files,omitempty"`
}

// StrelkaICSAttachment is the StrelkaICSAttachment component of the Message Data Model.
type StrelkaICSAttachment struct {

	// Extraction error message
	DecodeError *string `json:"decode_error,omitempty"`

	// Whether file was extracted
	Extracted *bool `json:"extracted,omitempty"`

	// Original filename
	Filename *string `json:"filename,omitempty"`

	// MIME type
	MIMEType *string `json:"mime_type,omitempty"`

	// File size in bytes
	Size *string `json:"size,omitempty"`

	// Attachment type
	Type *StrelkaICSAttachmentType `json:"type,omitempty"`

	// URI for external references
	URI *string `json:"uri,omitempty"`
}

// StrelkaICSAttendee is the StrelkaICSAttendee component of the Message Data Model.
type StrelkaICSAttendee struct {
	Mailbox *Mailbox `json:"mailbox,omitempty"`

	// Participation status
	Partstat *string `json:"partstat,omitempty"`

	// Attendee role
	Role *string `json:"role,omitempty"`

	// RSVP requested
	Rsvp *bool `json:"rsvp,omitempty"`
}

// StrelkaICSCalendar is the StrelkaICSCalendar component of the Message Data Model.
type StrelkaICSCalendar struct {

	// Calendar scale
	Calscale *string `json:"calscale,omitempty"`

	// Calendar components
	Components []*StrelkaICSComponent `json:"components,omitempty"`

	// Calendar method
	Method *string `json:"method,omitempty"`

	// Product identifier
	Prodid *string `json:"prodid,omitempty"`

	// iCalendar version
	Version *string `json:"version,omitempty"`
}

// StrelkaICSComponent is the StrelkaICSComponent component of the Message Data Model.
type StrelkaICSComponent struct {

	// File attachments
	Attachments []*StrelkaICSAttachment `json:"attachments,omitempty"`

	// Event attendees
	Attendees []*StrelkaICSAttendee `json:"attendees,omitempty"`

	// Classification
	Class *string `json:"class,omitempty"`

	// Creation date/time
	Created *string `json:"created,omitempty"`

	// Detailed description
	Description *string `json:"description,omitempty"`

	// End date/time
	Dtend *string `json:"dtend,omitempty"`

	// Creation timestamp
	Dtstamp *string `json:"dtstamp,omitempty"`

	// Start date/time
	Dtstart *string `json:"dtstart,omitempty"`

	// Duration in human-readable format
	Duration *string `json:"duration,omitempty"`

	// Last modification date/time
	LastModified *string `json:"last_modified,omitempty"`

	// Event location
	Location *string `json:"location,omitempty"`

	// Event organizers
	Organizers []*StrelkaICSOrganizer `json:"organizers,omitempty"`

	// Priority level (0-9)
	Priority *string `json:"priority,omitempty"`

	// Revision sequence
	Sequence *string `json:"sequence,omitempty"`

	// Event status
	Status *string `json:"status,omitempty"`

	// Brief description
	Summary *string `json:"summary,omitempty"`

	// Transparency
	Transp *string `json:"transp,omitempty"`

	// Component type
	Type *StrelkaICSComponentType `json:"type,omitempty"`

	// Unique identifier
	Uid *string `json:"uid,omitempty"`

	// Referenced URLs
	URLs []*URL `json:"urls,omitempty"`
}

// StrelkaICSOrganizer is the StrelkaICSOrganizer component of the Message Data Model.
type StrelkaICSOrganizer struct {
	Mailbox *Mailbox `json:"mailbox,omitempty"`
}

// StrelkaICSTotal summary counts for calendar components
type StrelkaICSTotal struct {

	// Total VALARM components
	Alarms *int64 `json:"alarms,omitempty"`

	// Total ATTACH properties
	Attachments *int64 `json:"attachments,omitempty"`

	// Total attendees across all components
	Attendees *int64 `json:"attendees,omitempty"`

	// Total calendar components
	Components *int64 `json:"components,omitempty"`

	// Total VEVENT components
	Events *int64 `json:"events,omitempty"`

	// Successfully extracted files
	ExtractedFiles *int64 `json:"extracted_files,omitempty"`

	// Total VJOURNAL components
	Journals *int64 `json:"journals,omitempty"`

	// Total organizers across all components
	Organizers *int64 `json:"organizers,omitempty"`

	// Total VTIMEZONE components
	Timezones *int64 `json:"timezones,omitempty"`

	// Total VTODO components
	Todos *int64 `json:"todos,omitempty"`

	// Total URL properties
	URLs *int64 `json:"urls,omitempty"`
}

// StrelkaJavascript contains details about the types of elements found in a JS script. Very simple scripts
// might signal obfuscation.
type StrelkaJavascript struct {

	// All unique identifiers present in JS. unescape and write may be considered suspicious;
	// a variable name is also an identifier.
	Identifiers []string `json:"identifiers,omitempty"`

	// All unique keywords present in JS, e.g. 'if'.
	Keywords []string `json:"keywords,omitempty"`

	// All unique regular expressions present JS.
	RegularExpressions []string `json:"regular_expressions,omitempty"`

	// All unique strings present in JS.
	Strings []string `json:"strings,omitempty"`

	// All unique tokens/types present in JS. The other values in this type would be present
	// in this list if they occur at all. E.g. a simple script may contain just Identifier &
	// Punctuator (punctuator is not included any further)
	Tokens []string `json:"tokens,omitempty"`
}

// StrelkaJpegGif extracts contents past the GIF trailer for further processing. Empty if there's no data
// based trailer.
type StrelkaJpegGif struct {
	TrailerIndex *int64 `json:"trailer_index,omitempty"`
}

// StrelkaKeyVal is the StrelkaKeyVal component of the Message Data Model.
type StrelkaKeyVal struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// StrelkaLNK extracted details from LNK files. See ExifTools too.
type StrelkaLNK struct {
	MAC                  *string `json:"MAC,omitempty"`
	CommandLineArguments *string `json:"command_line_arguments,omitempty"`
	DriveSerialNumber    *string `json:"drive_serial_number,omitempty"`
	DriveType            *string `json:"drive_type,omitempty"`
	LocalBasePath        *string `json:"local_base_path,omitempty"`
	MachineID            *string `json:"machine_id,omitempty"`
	RelativePath         *string `json:"relative_path,omitempty"`
	VolumeLabel          *string `json:"volume_label,omitempty"`
	WorkingDir           *string `json:"working_dir,omitempty"`
}

// StrelkaLibArchive unpacks archives supported by libarchive (including ISO files). Reports totals
type StrelkaLibArchive struct {
	TotalExtracted *int64 `json:"total_extracted,omitempty"`
	TotalFiles     *int64 `json:"total_files,omitempty"`
}

// StrelkaMachO unpacks and inspects Mach Objects (executables, libraries, etc)
type StrelkaMachO struct {

	// All commands within
	Commands         []string       `json:"commands,omitempty"`
	HasCodeSignature *bool          `json:"has_code_signature,omitempty"`
	Header           map[string]any `json:"header,omitempty"`

	// Dylinker command name used
	LoadDylinkerName *string `json:"load_dylinker_name,omitempty"`

	// Binary has NX (non-executable stack) protection
	Nx *bool `json:"nx,omitempty"`

	// Binary is position independent
	Pie *bool `json:"pie,omitempty"`

	// 5 part source version
	SourceVersion *string `json:"source_version,omitempty"`

	// Details about symbols within binary
	Symbols map[string]any `json:"symbols,omitempty"`

	// Number of binaries registered
	TotalBinaries *int64 `json:"total_binaries,omitempty"`

	// Number of load commands
	TotalCommands *int64 `json:"total_commands,omitempty"`

	// Number of libraries/Dylib commands
	TotalLibraries *int64 `json:"total_libraries,omitempty"`

	// Number of relocations
	TotalRelocations *int64 `json:"total_relocations,omitempty"`

	// Number of sections
	TotalSections *int64 `json:"total_sections,omitempty"`

	// Number of segments
	TotalSegments *int64 `json:"total_segments,omitempty"`

	// Number of symbols
	TotalSymbols *int64 `json:"total_symbols,omitempty"`
}

// StrelkaOCR attempts to find text in images and explodes the text for further scanning.
type StrelkaOCR struct {

	// Full text returned from OCR, including whitespace
	Raw *string `json:"raw,omitempty"`

	// Array of words found by OCR
	Text []string `json:"text,omitempty"`
}

// StrelkaOle unpacks valid OLE files. Reports total files.
type StrelkaOle struct {
	TotalExtracted *int64 `json:"total_extracted,omitempty"`
}

// StrelkaOnenote INTERNAL
type StrelkaOnenote struct {
}

// StrelkaPDF unpacks a PDF for further processing. Reports total files.
type StrelkaPDF struct {

	// URLs which could not be parsed
	InvalidURLs    []string `json:"invalid_urls,omitempty"`
	TotalExtracted *int64   `json:"total_extracted,omitempty"`

	// Detected URLs
	URLs []*URL `json:"urls,omitempty"`
}

// StrelkaPDFObjHash generates PDF Object Hash of the given PDF file
type StrelkaPDFObjHash struct {

	// Hash string used to generate the object hash for the PDF
	HashString *string `json:"hash_string,omitempty"`

	// Object hash of the PDF. This is the hash of the object types present in the document.
	ObjectHash *string `json:"object_hash,omitempty"`
}

// StrelkaPPTX extracts details for a powerpoint (pptx) document, and explodes the text for further
// scanning.
type StrelkaPPTX struct {
	Author     *string    `json:"author,omitempty"`
	Category   *string    `json:"category,omitempty"`
	Comments   *string    `json:"comments,omitempty"`
	Created    *time.Time `json:"created,omitempty"`
	ImageCount *int64     `json:"image_count,omitempty"`

	// URLs which could not be parsed
	InvalidURLs    []string   `json:"invalid_urls,omitempty"`
	Keywords       *string    `json:"keywords,omitempty"`
	LastModifiedBy *string    `json:"last_modified_by,omitempty"`
	LastPrinted    *time.Time `json:"last_printed,omitempty"`
	Modified       *time.Time `json:"modified,omitempty"`
	Revision       *int64     `json:"revision,omitempty"`
	SlideCount     *int64     `json:"slide_count,omitempty"`
	Subject        *string    `json:"subject,omitempty"`
	Title          *string    `json:"title,omitempty"`

	// Detected URLs
	URLs      []*URL `json:"urls,omitempty"`
	WordCount *int64 `json:"word_count,omitempty"`
}

// StrelkaQR checks for QR codes and evaluates them
type StrelkaQR struct {

	// Raw UTF8 Data
	Data *string `json:"data,omitempty"`

	// Type of content, if known
	Type *StrelkaQRType `json:"type,omitempty"`
	URL  *URL           `json:"url,omitempty"`
}

// StrelkaRTF unpacks RTF files. Reports totals
type StrelkaRTF struct {
	TotalExtracted *int64 `json:"total_extracted,omitempty"`
}

// StrelkaRar unpacks rar files. Reports totals
type StrelkaRar struct {
	HostOs         *string `json:"host_os,omitempty"`
	TotalExtracted *int64  `json:"total_extracted,omitempty"`
	TotalFiles     *int64  `json:"total_files,omitempty"`
}

// FileExplodeOutput is the StrelkaResponse component of the Message Data Model.
type FileExplodeOutput struct {

	// depth in explosion, starts at 0
	Depth *int64 `json:"depth,omitempty"`

	// file extension if known. Using YARA and MIME rules (see .flavors) may provide more
	// accurate detections.
	FileExtension *string `json:"file_extension,omitempty"`

	// name of the file, or a placeholder. For files exploded from an archive this will be the
	// actual name, but for extracted text, octet stream etc, it will be assigned by the
	// parent to something arbitrary.
	FileName *string         `json:"file_name,omitempty"`
	Flavors  *StrelkaFlavors `json:"flavors,omitempty"`

	// ID representing this file in the tree
	NodeID *string `json:"node_id,omitempty"`

	// ID of parent, or not present for the root
	ParentNodeID *string   `json:"parent_node_id,omitempty"`
	Scan         *FileScan `json:"scan,omitempty"`

	// file size in bytes
	Size *int64 `json:"size,omitempty"`

	// Scanner which 'exploded' this file
	Source *string `json:"source,omitempty"`
}

// FileScan contains results of all available bin explode scanners. Some scanners explode embedded
// binaries more than offer scan/analysis. Some of these have total_extracted &
// total_unextracted (the count of any files remaining after limits are hit). Some
// exploding scanners have limited analyses, besides the insight into the count of
// embedded files (see ZIP). RawOCR is an example which explodes, but does not report
// totals & explodes content which isn't truly an embedded file.
type FileScan struct {
	Bzip2            *StrelkaBZip2        `json:"bzip2,omitempty"`
	Docx             *StrelkaDocX         `json:"docx,omitempty"`
	EncryptedDoc     *StrelkaEncryptedDoc `json:"encrypted_doc,omitempty"`
	EncryptedPdf     *StrelkaEncryptedPdf `json:"encrypted_pdf,omitempty"`
	EncryptedZip     *StrelkaEncryptedZip `json:"encrypted_zip,omitempty"`
	Entropy          *StrelkaEntropy      `json:"entropy,omitempty"`
	Exiftool         *StrelkaExifTool     `json:"exiftool,omitempty"`
	Gif              *StrelkaJpegGif      `json:"gif,omitempty"`
	Gzip             *StrelkaGZip         `json:"gzip,omitempty"`
	Hash             *StrelkaHash         `json:"hash,omitempty"`
	HTML             *StrelkaHTML         `json:"html,omitempty"`
	Ics              *StrelkaICS          `json:"ics,omitempty"`
	Javascript       *StrelkaJavascript   `json:"javascript,omitempty"`
	Jpeg             *StrelkaJpegGif      `json:"jpeg,omitempty"`
	Libarchive       *StrelkaLibArchive   `json:"libarchive,omitempty"`
	Lnk              *StrelkaLNK          `json:"lnk,omitempty"`
	Macho            *StrelkaMachO        `json:"macho,omitempty"`
	Ocr              *StrelkaOCR          `json:"ocr,omitempty"`
	Ole              *StrelkaOle          `json:"ole,omitempty"`
	Onenote          *StrelkaOnenote      `json:"onenote,omitempty"`
	Pdf              *StrelkaPDF          `json:"pdf,omitempty"`
	PdfObjHash       *StrelkaPDFObjHash   `json:"pdf_obj_hash,omitempty"`
	Pptx             *StrelkaPPTX         `json:"pptx,omitempty"`
	Qr               *StrelkaQR           `json:"qr,omitempty"`
	Rar              *StrelkaRar          `json:"rar,omitempty"`
	Rtf              *StrelkaRTF          `json:"rtf,omitempty"`
	SensitivityLabel *SensitivityLabel    `json:"sensitivity_label,omitempty"`
	Strings          *StrelkaStrings      `json:"strings,omitempty"`
	Tar              *StrelkaTar          `json:"tar,omitempty"`
	URL              *StrelkaURL          `json:"url,omitempty"`
	Vba              *StrelkaVBA          `json:"vba,omitempty"`
	Xlsx             *StrelkaXLSX         `json:"xlsx,omitempty"`
	Xml              *StrelkaXML          `json:"xml,omitempty"`
	Yara             *StrelkaYARA         `json:"yara,omitempty"`
	Zip              *StrelkaZip          `json:"zip,omitempty"`
	Zlib             *StrelkaZLib         `json:"zlib,omitempty"`
}

// StrelkaStrings simply finds and extracts any strings from.
type StrelkaStrings struct {

	// If the entire input is a string, mirror the input as a single string.
	Raw *string `json:"raw,omitempty"`

	// All detected strings.
	Strings []string `json:"strings,omitempty"`
}

// StrelkaTar unpacks tar files. Reports totals
type StrelkaTar struct {
	TotalExtracted *int64 `json:"total_extracted,omitempty"`
	TotalFiles     *int64 `json:"total_files,omitempty"`
}

// StrelkaURL detects URLs from text (generally text unpacked by other scanners).
type StrelkaURL struct {

	// URLs which could not be parsed
	InvalidURLs []string `json:"invalid_urls,omitempty"`

	// Detected URLs.
	URLs []*URL `json:"urls,omitempty"`
}

// StrelkaVBA examines VBA macros in Ole files, and unpacks macro code for further analysis.
type StrelkaVBA struct {

	// All keywords associated with auto exec macros
	AutoExec []string `json:"auto_exec,omitempty"`

	// Decoded base64 strings
	Base64 []string `json:"base64,omitempty"`

	// Decoded dridex strings
	Dridex []string `json:"dridex,omitempty"`

	// Decoded hex strings
	Hex []string `json:"hex,omitempty"`

	// String values of indicators, such as 'cmd.exe'
	Ioc []string `json:"ioc,omitempty"`

	// Reported descriptions of suspicious behavior, e.g. 'Run' or 'Hex Strings'
	Suspicious     []string `json:"suspicious,omitempty"`
	TotalExtracted *int64   `json:"total_extracted,omitempty"`
	TotalFiles     *int64   `json:"total_files,omitempty"`

	// Decoded vba obfuscated strings
	VbaObfuscated []string `json:"vba_obfuscated,omitempty"`
}

// StrelkaXLSX INTERNAL
type StrelkaXLSX struct {
	Author        *string    `json:"author,omitempty"`
	Category      *string    `json:"category,omitempty"`
	Comments      *string    `json:"comments,omitempty"`
	ContentStatus *string    `json:"content_status,omitempty"`
	Created       *time.Time `json:"created,omitempty"`
	Identifier    *string    `json:"identifier,omitempty"`

	// URLs which could not be parsed
	InvalidURLs    []string                `json:"invalid_urls,omitempty"`
	Keywords       *string                 `json:"keywords,omitempty"`
	Language       *string                 `json:"language,omitempty"`
	LastModifiedBy *string                 `json:"last_modified_by,omitempty"`
	LastPrinted    *time.Time              `json:"last_printed,omitempty"`
	Modified       *time.Time              `json:"modified,omitempty"`
	Revision       *int64                  `json:"revision,omitempty"`
	SheetNames     []*StrelkaXLSXSheetInfo `json:"sheet_names,omitempty"`
	Subject        *string                 `json:"subject,omitempty"`
	Title          *string                 `json:"title,omitempty"`

	// Detected URLs
	URLs      []*URL  `json:"urls,omitempty"`
	Version   *string `json:"version,omitempty"`
	WordCount *int64  `json:"word_count,omitempty"`
}

// StrelkaXLSXSheetInfo is the StrelkaXLSXSheetInfo component of the Message Data Model.
type StrelkaXLSXSheetInfo struct {

	// Sheet name.
	Name *string `json:"name,omitempty"`

	// False if Excel marks this sheet hidden or very-hidden.
	Visible *bool `json:"visible,omitempty"`
}

// StrelkaXML finds namespaces and other details from XML
type StrelkaXML struct {

	// DOCTYPE declaration from file
	DocType        *string  `json:"doc_type,omitempty"`
	Namespaces     []string `json:"namespaces,omitempty"`
	Tags           []string `json:"tags,omitempty"`
	TotalExtracted *int64   `json:"total_extracted,omitempty"`

	// XML version as declared by the document
	Version *string `json:"version,omitempty"`
}

// StrelkaYARA reports YARA results from custom installed YARA rules.
type StrelkaYARA struct {
	Flags   []string            `json:"flags,omitempty"`
	Matches []*StrelkaYARAMatch `json:"matches,omitempty"`
}

// StrelkaYARAMatch is the StrelkaYARAMatch component of the Message Data Model.
type StrelkaYARAMatch struct {
	Meta map[string]string `json:"meta,omitempty"`
	Name *string           `json:"name,omitempty"`
}

// StrelkaZLib unpacks zlib files. Reports size
type StrelkaZLib struct {

	// Size of uncompressed file within.
	Size *int64 `json:"size,omitempty"`
}

// StrelkaZip unpacks ZIP files. Reports total files.
type StrelkaZip struct {

	// All member paths included in the zip (files and folders)
	AllPaths []string `json:"all_paths,omitempty"`

	// File names, including path, which the scanner attempted to open (cuts off at a limit)
	AttemptedFiles []string `json:"attempted_files,omitempty"`

	// True if known to be encrypted. scan.encrypted_zip can contain details if password is
	// bypassed.
	Encrypted      *bool  `json:"encrypted,omitempty"`
	TotalExtracted *int64 `json:"total_extracted,omitempty"`
	TotalFiles     *int64 `json:"total_files,omitempty"`
}
