// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by "go run ./mdm/gen"; DO NOT EDIT.
//
// Source: mdm.openapi.json, vendored from Sublime Security's published API reference.

package mdm

import "time"

// AttachmentFileType enumerates the values upstream documents for this field.
//
// # File type determined by looking at the magic bytes in the file
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type AttachmentFileType string

const (
	AttachmentFileTypeN3gp    AttachmentFileType = "3gp"
	AttachmentFileTypeN7z     AttachmentFileType = "7z"
	AttachmentFileTypeZ       AttachmentFileType = "Z"
	AttachmentFileTypeAac     AttachmentFileType = "aac"
	AttachmentFileTypeAiff    AttachmentFileType = "aiff"
	AttachmentFileTypeAmr     AttachmentFileType = "amr"
	AttachmentFileTypeAr      AttachmentFileType = "ar"
	AttachmentFileTypeAvi     AttachmentFileType = "avi"
	AttachmentFileTypeBmp     AttachmentFileType = "bmp"
	AttachmentFileTypeBz2     AttachmentFileType = "bz2"
	AttachmentFileTypeCab     AttachmentFileType = "cab"
	AttachmentFileTypeCr2     AttachmentFileType = "cr2"
	AttachmentFileTypeCrx     AttachmentFileType = "crx"
	AttachmentFileTypeDcm     AttachmentFileType = "dcm"
	AttachmentFileTypeDeb     AttachmentFileType = "deb"
	AttachmentFileTypeDex     AttachmentFileType = "dex"
	AttachmentFileTypeDey     AttachmentFileType = "dey"
	AttachmentFileTypeDoc     AttachmentFileType = "doc"
	AttachmentFileTypeDocx    AttachmentFileType = "docx"
	AttachmentFileTypeDwg     AttachmentFileType = "dwg"
	AttachmentFileTypeElf     AttachmentFileType = "elf"
	AttachmentFileTypeEot     AttachmentFileType = "eot"
	AttachmentFileTypeEpub    AttachmentFileType = "epub"
	AttachmentFileTypeExe     AttachmentFileType = "exe"
	AttachmentFileTypeFlac    AttachmentFileType = "flac"
	AttachmentFileTypeFlv     AttachmentFileType = "flv"
	AttachmentFileTypeGif     AttachmentFileType = "gif"
	AttachmentFileTypeGz      AttachmentFileType = "gz"
	AttachmentFileTypeHeif    AttachmentFileType = "heif"
	AttachmentFileTypeHTML    AttachmentFileType = "html"
	AttachmentFileTypeIco     AttachmentFileType = "ico"
	AttachmentFileTypeIcs     AttachmentFileType = "ics"
	AttachmentFileTypeIso     AttachmentFileType = "iso"
	AttachmentFileTypeJp2     AttachmentFileType = "jp2"
	AttachmentFileTypeJpg     AttachmentFileType = "jpg"
	AttachmentFileTypeJxr     AttachmentFileType = "jxr"
	AttachmentFileTypeLz      AttachmentFileType = "lz"
	AttachmentFileTypeM4a     AttachmentFileType = "m4a"
	AttachmentFileTypeM4v     AttachmentFileType = "m4v"
	AttachmentFileTypeMacho   AttachmentFileType = "macho"
	AttachmentFileTypeMid     AttachmentFileType = "mid"
	AttachmentFileTypeMkv     AttachmentFileType = "mkv"
	AttachmentFileTypeMov     AttachmentFileType = "mov"
	AttachmentFileTypeMp3     AttachmentFileType = "mp3"
	AttachmentFileTypeMp4     AttachmentFileType = "mp4"
	AttachmentFileTypeMpg     AttachmentFileType = "mpg"
	AttachmentFileTypeNes     AttachmentFileType = "nes"
	AttachmentFileTypeOgg     AttachmentFileType = "ogg"
	AttachmentFileTypeOtf     AttachmentFileType = "otf"
	AttachmentFileTypePdf     AttachmentFileType = "pdf"
	AttachmentFileTypePng     AttachmentFileType = "png"
	AttachmentFileTypePpt     AttachmentFileType = "ppt"
	AttachmentFileTypePptx    AttachmentFileType = "pptx"
	AttachmentFileTypePs      AttachmentFileType = "ps"
	AttachmentFileTypePsd     AttachmentFileType = "psd"
	AttachmentFileTypeRar     AttachmentFileType = "rar"
	AttachmentFileTypeRpm     AttachmentFileType = "rpm"
	AttachmentFileTypeRtf     AttachmentFileType = "rtf"
	AttachmentFileTypeSqlite  AttachmentFileType = "sqlite"
	AttachmentFileTypeSvg     AttachmentFileType = "svg"
	AttachmentFileTypeSwf     AttachmentFileType = "swf"
	AttachmentFileTypeTar     AttachmentFileType = "tar"
	AttachmentFileTypeTif     AttachmentFileType = "tif"
	AttachmentFileTypeTtf     AttachmentFileType = "ttf"
	AttachmentFileTypeWasm    AttachmentFileType = "wasm"
	AttachmentFileTypeWav     AttachmentFileType = "wav"
	AttachmentFileTypeWebm    AttachmentFileType = "webm"
	AttachmentFileTypeWebp    AttachmentFileType = "webp"
	AttachmentFileTypeWmv     AttachmentFileType = "wmv"
	AttachmentFileTypeWoff    AttachmentFileType = "woff"
	AttachmentFileTypeWoff2   AttachmentFileType = "woff2"
	AttachmentFileTypeXls     AttachmentFileType = "xls"
	AttachmentFileTypeXlsx    AttachmentFileType = "xlsx"
	AttachmentFileTypeXz      AttachmentFileType = "xz"
	AttachmentFileTypeZip     AttachmentFileType = "zip"
	AttachmentFileTypeZst     AttachmentFileType = "zst"
	AttachmentFileTypeUnknown AttachmentFileType = "unknown"
)

// AuthResultsDKIM enumerates the values upstream documents for this field.
//
// # Verdict of the Domain Keys Identified Mail check
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type AuthResultsDKIM string

const (
	AuthResultsDKIMNone      AuthResultsDKIM = "none"
	AuthResultsDKIMPass      AuthResultsDKIM = "pass"
	AuthResultsDKIMFail      AuthResultsDKIM = "fail"
	AuthResultsDKIMPolicy    AuthResultsDKIM = "policy"
	AuthResultsDKIMNeutral   AuthResultsDKIM = "neutral"
	AuthResultsDKIMTemperror AuthResultsDKIM = "temperror"
	AuthResultsDKIMPermerror AuthResultsDKIM = "permerror"
)

// AuthResultsDMARC enumerates the values upstream documents for this field.
//
// Verdict of the Domain-based Message Authentication, Reporting & Conformance check
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type AuthResultsDMARC string

const (
	AuthResultsDMARCNone          AuthResultsDMARC = "none"
	AuthResultsDMARCPass          AuthResultsDMARC = "pass"
	AuthResultsDMARCFail          AuthResultsDMARC = "fail"
	AuthResultsDMARCBestguesspass AuthResultsDMARC = "bestguesspass"
)

// AuthResultsSPF enumerates the values upstream documents for this field.
//
// # Verdict of the Sender Policy Framework
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type AuthResultsSPF string

const (
	AuthResultsSPFNone      AuthResultsSPF = "none"
	AuthResultsSPFPass      AuthResultsSPF = "pass"
	AuthResultsSPFFail      AuthResultsSPF = "fail"
	AuthResultsSPFSoftfail  AuthResultsSPF = "softfail"
	AuthResultsSPFPolicy    AuthResultsSPF = "policy"
	AuthResultsSPFNeutral   AuthResultsSPF = "neutral"
	AuthResultsSPFTemperror AuthResultsSPF = "temperror"
	AuthResultsSPFPermerror AuthResultsSPF = "permerror"
)

// ExternalRouteType enumerates the values upstream documents for this field.
//
// whether the message was sent or received
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type ExternalRouteType string

const (
	ExternalRouteTypeSent     ExternalRouteType = "sent"
	ExternalRouteTypeReceived ExternalRouteType = "received"
)

// IPTranslationEncoders enumerates the values upstream documents for this field.
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type IPTranslationEncoders string

const (
	IPTranslationEncodersHex            IPTranslationEncoders = "hex"
	IPTranslationEncodersOctal          IPTranslationEncoders = "octal"
	IPTranslationEncodersDecimalInteger IPTranslationEncoders = "decimal_integer"
	IPTranslationEncodersDotted         IPTranslationEncoders = "dotted"
	IPTranslationEncodersMixedRadix     IPTranslationEncoders = "mixed_radix"
)

// LinkParser enumerates the values upstream documents for this field.
//
// # The parser that was used to derived the link
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type LinkParser string

const (
	LinkParserPlain     LinkParser = "plain"
	LinkParserHyperlink LinkParser = "hyperlink"
)

// RewriteDetailsEncoders enumerates the values upstream documents for this field.
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type RewriteDetailsEncoders string

const (
	RewriteDetailsEncodersAct                         RewriteDetailsEncoders = "act"
	RewriteDetailsEncodersAdobe                       RewriteDetailsEncoders = "adobe"
	RewriteDetailsEncodersAppspot                     RewriteDetailsEncoders = "appspot"
	RewriteDetailsEncodersAwsSes                      RewriteDetailsEncoders = "aws_ses"
	RewriteDetailsEncodersAzurecomm                   RewriteDetailsEncoders = "azurecomm"
	RewriteDetailsEncodersAzureSafelink               RewriteDetailsEncoders = "azure_safelink"
	RewriteDetailsEncodersBarracuda                   RewriteDetailsEncoders = "barracuda"
	RewriteDetailsEncodersBingOpenRedirect            RewriteDetailsEncoders = "bing_open_redirect"
	RewriteDetailsEncodersBranchIo                    RewriteDetailsEncoders = "branch_io"
	RewriteDetailsEncodersCheckpoint                  RewriteDetailsEncoders = "checkpoint"
	RewriteDetailsEncodersCisco                       RewriteDetailsEncoders = "cisco"
	RewriteDetailsEncodersCloudflare                  RewriteDetailsEncoders = "cloudflare"
	RewriteDetailsEncodersConvertkit                  RewriteDetailsEncoders = "convertkit"
	RewriteDetailsEncodersCustomerio                  RewriteDetailsEncoders = "customerio"
	RewriteDetailsEncodersDerefMail                   RewriteDetailsEncoders = "deref_mail"
	RewriteDetailsEncodersDoubleclick                 RewriteDetailsEncoders = "doubleclick"
	RewriteDetailsEncodersEdgepilot                   RewriteDetailsEncoders = "edgepilot"
	RewriteDetailsEncodersEgress                      RewriteDetailsEncoders = "egress"
	RewriteDetailsEncodersEsvalabs                    RewriteDetailsEncoders = "esvalabs"
	RewriteDetailsEncodersExactag                     RewriteDetailsEncoders = "exactag"
	RewriteDetailsEncodersExclaimer                   RewriteDetailsEncoders = "exclaimer"
	RewriteDetailsEncodersFacebook                    RewriteDetailsEncoders = "facebook"
	RewriteDetailsEncodersFireeye                     RewriteDetailsEncoders = "fireeye"
	RewriteDetailsEncodersFortimail                   RewriteDetailsEncoders = "fortimail"
	RewriteDetailsEncodersGenericDesturl              RewriteDetailsEncoders = "generic_desturl"
	RewriteDetailsEncodersGenericLogoutRedirect       RewriteDetailsEncoders = "generic_logout_redirect"
	RewriteDetailsEncodersGoAcoustic                  RewriteDetailsEncoders = "go_acoustic"
	RewriteDetailsEncodersGoogleAmp                   RewriteDetailsEncoders = "google_amp"
	RewriteDetailsEncodersGoogleAmpProject            RewriteDetailsEncoders = "google_amp_project"
	RewriteDetailsEncodersGoogleAdservices            RewriteDetailsEncoders = "google_adservices"
	RewriteDetailsEncodersGoogleAdditnowOpenRedirect  RewriteDetailsEncoders = "google_additnow_open_redirect"
	RewriteDetailsEncodersGoogleMeetRedirect          RewriteDetailsEncoders = "google_meet_redirect"
	RewriteDetailsEncodersGoogleNotifications         RewriteDetailsEncoders = "google_notifications"
	RewriteDetailsEncodersGoogleOpenRedirect          RewriteDetailsEncoders = "google_open_redirect"
	RewriteDetailsEncodersGoogleTagManager            RewriteDetailsEncoders = "google_tag_manager"
	RewriteDetailsEncodersGoogleTravelRedirect        RewriteDetailsEncoders = "google_travel_redirect"
	RewriteDetailsEncodersGoogleTranslateOpenRedirect RewriteDetailsEncoders = "google_translate_open_redirect"
	RewriteDetailsEncodersGoogleUserContent           RewriteDetailsEncoders = "google_user_content"
	RewriteDetailsEncodersHornetsecurity              RewriteDetailsEncoders = "hornetsecurity"
	RewriteDetailsEncodersHrefLi                      RewriteDetailsEncoders = "href_li"
	RewriteDetailsEncodersIndeedOpenRedirect          RewriteDetailsEncoders = "indeed_open_redirect"
	RewriteDetailsEncodersInky                        RewriteDetailsEncoders = "inky"
	RewriteDetailsEncodersInstagram                   RewriteDetailsEncoders = "instagram"
	RewriteDetailsEncodersMailchimp                   RewriteDetailsEncoders = "mailchimp"
	RewriteDetailsEncodersMailgun                     RewriteDetailsEncoders = "mailgun"
	RewriteDetailsEncodersMailinblack                 RewriteDetailsEncoders = "mailinblack"
	RewriteDetailsEncodersMailjet                     RewriteDetailsEncoders = "mailjet"
	RewriteDetailsEncodersMailmarshal                 RewriteDetailsEncoders = "mailmarshal"
	RewriteDetailsEncodersMandrill                    RewriteDetailsEncoders = "mandrill"
	RewriteDetailsEncodersMessagegears                RewriteDetailsEncoders = "messagegears"
	RewriteDetailsEncodersMicrosoft                   RewriteDetailsEncoders = "microsoft"
	RewriteDetailsEncodersMicrosoftDynamics           RewriteDetailsEncoders = "microsoft_dynamics"
	RewriteDetailsEncodersMicrosoftOauthRedirect      RewriteDetailsEncoders = "microsoft_oauth_redirect"
	RewriteDetailsEncodersMondayTracker               RewriteDetailsEncoders = "monday_tracker"
	RewriteDetailsEncodersPostmark                    RewriteDetailsEncoders = "postmark"
	RewriteDetailsEncodersPpcprotect                  RewriteDetailsEncoders = "ppcprotect"
	RewriteDetailsEncodersProofpoint                  RewriteDetailsEncoders = "proofpoint"
	RewriteDetailsEncodersPylonlinks                  RewriteDetailsEncoders = "pylonlinks"
	RewriteDetailsEncodersSecurence                   RewriteDetailsEncoders = "securence"
	RewriteDetailsEncodersSophos                      RewriteDetailsEncoders = "sophos"
	RewriteDetailsEncodersSqclick                     RewriteDetailsEncoders = "sqclick"
	RewriteDetailsEncodersSquarespace                 RewriteDetailsEncoders = "squarespace"
	RewriteDetailsEncodersStaffbase                   RewriteDetailsEncoders = "staffbase"
	RewriteDetailsEncodersSublime                     RewriteDetailsEncoders = "sublime"
	RewriteDetailsEncodersTitanhq                     RewriteDetailsEncoders = "titanhq"
	RewriteDetailsEncodersTopsec                      RewriteDetailsEncoders = "topsec"
	RewriteDetailsEncodersTrendMicro                  RewriteDetailsEncoders = "trend_micro"
	RewriteDetailsEncodersVadeSecure                  RewriteDetailsEncoders = "vade_secure"
	RewriteDetailsEncodersVtiger                      RewriteDetailsEncoders = "vtiger"
	RewriteDetailsEncodersWix                         RewriteDetailsEncoders = "wix"
	RewriteDetailsEncodersWordpressTnp                RewriteDetailsEncoders = "wordpress_tnp"
	RewriteDetailsEncodersYahoo                       RewriteDetailsEncoders = "yahoo"
	RewriteDetailsEncodersYoutubeSetSid               RewriteDetailsEncoders = "youtube_set_sid"
	RewriteDetailsEncodersCloudflareOne               RewriteDetailsEncoders = "cloudflare_one"
)

// SenderMailboxDecoders enumerates the values upstream documents for this field.
//
// Unknown values are preserved rather than rejected: a message that arrives with a
// value we do not recognise is still a message we must evaluate rules against.
type SenderMailboxDecoders string

const (
	SenderMailboxDecodersGoogleGroups SenderMailboxDecoders = "google_groups"
	SenderMailboxDecodersIcsSentBy    SenderMailboxDecoders = "ics_sent_by"
)

// Attachment is the Mdm_serviceAttachment component of the Message Data Model.
type Attachment struct {

	// Content-Disposition type, typically 'attachment' or 'inline'
	ContentDisposition *string `json:"content_disposition,omitempty"`

	// Content-ID extracted from the MIME payload; is stripped of leading and trailing <>
	// characters
	ContentID *string `json:"content_id,omitempty"`

	// Content-Transfer-Encoding extracted from the MIME payload
	ContentTransferEncoding *string `json:"content_transfer_encoding,omitempty"`

	// Content-Type extracted from the MIME payload
	ContentType *string `json:"content_type,omitempty"`

	// File extension from context such as headers
	FileExtension *string `json:"file_extension,omitempty"`

	// File name
	FileName *string `json:"file_name,omitempty"`

	// File type determined by looking at the magic bytes in the file
	FileType *AttachmentFileType `json:"file_type,omitempty"`

	// MD5 hash of the raw contents
	MD5 *string `json:"md5,omitempty"`

	// Base64 encoded source of the file
	Raw []byte `json:"raw,omitempty"`

	// SHA1 hash of the raw contents
	SHA1 *string `json:"sha1,omitempty"`

	// SHA256 hash of the raw contents
	SHA256 *string `json:"sha256,omitempty"`

	// Size of the file in bytes
	Size *int64 `json:"size,omitempty"`
}

// AuthResults results of authentication. Supported fields include 'Authentication-Results',
// 'X-Original-Authentication-Results', 'X-MS-Exchange-Authentication-Results',
// 'X-Agari-Authentication-Results', 'Authentication-Results-Original', and
// 'ARC-Authentication-Results'. Specification details can be found at
// https://tools.ietf.org/html/rfc8601
type AuthResults struct {
	Compauth *CompAuth `json:"compauth,omitempty"`

	// Verdict of the Domain Keys Identified Mail check
	DKIM *AuthResultsDKIM `json:"dkim,omitempty"`

	// List of details of the Domain Keys Identified Mail checks
	DKIMDetails []*Signature `json:"dkim_details,omitempty"`

	// Verdict of the Domain-based Message Authentication, Reporting & Conformance check
	DMARC        *AuthResultsDMARC `json:"dmarc,omitempty"`
	DMARCDetails *DMARC            `json:"dmarc_details,omitempty"`

	// Instance number of this auth result (if ARC)
	Instance *string `json:"instance,omitempty"`
	Server   *Domain `json:"server,omitempty"`

	// Verdict of the Sender Policy Framework
	SPF        *AuthResultsSPF `json:"spf,omitempty"`
	SPFDetails *SPF            `json:"spf_details,omitempty"`

	// The type of authentication result, derived from the field name
	Type *string `json:"type,omitempty"`
}

// AuthSummary summary of authentication results for the message
type AuthSummary struct {
	DMARC *DMARCSummary `json:"dmarc,omitempty"`
	SPF   *SPFSummary   `json:"spf,omitempty"`
}

// Banner is the Mdm_serviceBanner component of the Message Data Model.
type Banner struct {

	// All links found in the banner, unique by the target and display text/url.
	Links []*Link `json:"links,omitempty"`

	// The text content from the warning banner.
	Text *string `json:"text,omitempty"`
}

// Body body of the email
type Body struct {
	CurrentThread *Thread   `json:"current_thread,omitempty"`
	HTML          *BodyHTML `json:"html,omitempty"`

	// IP Addresses located in the body
	IPs []*IP `json:"ips,omitempty"`

	// All links found in the body of the message, unique by the target and display text/url.
	Links []*Link `json:"links,omitempty"`
	Plain *Plain  `json:"plain,omitempty"`

	// The previous texts threads of the message'
	PreviousThreads []*PreviousThread `json:"previous_threads,omitempty"`
}

// BodyHTML the body part containing content-type text/html
type BodyHTML struct {

	// charset of the text/[subtype]
	Charset *string `json:"charset,omitempty"`

	// Content-Transfer-Encoding of the text/[subtype]
	ContentTransferEncoding *string `json:"content_transfer_encoding,omitempty"`

	// Visible text of the HTML document, with invisible characters removed and non-ASCII
	// characters converted to ASCII spaces.
	DisplayText *string `json:"display_text,omitempty"`

	// Inner text of the HTML document that doesn't include HTML tags.
	InnerText *string `json:"inner_text,omitempty"`

	// All links found in the HTML part of the body of the message
	Links []*Link `json:"links,omitempty"`

	// Decoded raw content of a body text type (text/[subtype] section)
	Raw *string `json:"raw,omitempty"`
}

// CompAuth composite Authentication result, used by Microsoft O365
type CompAuth struct {

	// Reason for the verdict
	Reason string `json:"reason,omitempty"`

	// Verdict of the compauth
	Verdict string `json:"verdict,omitempty"`
}

// DMARC details of the Domain-based Message Authentication, Reporting & Conformance check
type DMARC struct {

	// Indicates the action taken by the spam filter based on the results of the DMARC check.
	// For more information see
	// https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers?view=o365-worldwide#authentication-results-message-header-fields
	Action *string `json:"action,omitempty"`

	// Gmail-applied policy
	Disposition *string `json:"disposition,omitempty"`
	From        *Domain `json:"from,omitempty"`

	// Policy for the organizational domain
	Policy *string `json:"policy,omitempty"`

	// Policy for the subdomain of the organizational domain
	SubPolicy *string `json:"sub_policy,omitempty"`

	// Describes the results of the DMARC check for the message
	Verdict *string `json:"verdict,omitempty"`

	// DMARC version
	Version *string `json:"version,omitempty"`
}

// DMARCSummary summary of the DMARC check
type DMARCSummary struct {
	Details *DMARC `json:"details,omitempty"`

	// Whether the DMARC check errored
	Error *bool `json:"error,omitempty"`

	// Whether the DMARC check passed
	Pass *bool `json:"pass,omitempty"`

	// The lowest hop at which the DMARC check was made
	ReceivedHop *int64 `json:"received_hop,omitempty"`
}

// Domain domain parsed from X-Authenticated-Domain or X-Authenticated-Sender headers, which
// represents the domain used for sender authentication, typically the domain of the
// sending organization. This field provides additional context for analyzing the
// legitimacy of the sender
type Domain struct {

	// The fully qualified domain name (FQDN). This may not *always* be routable, e.g. when an
	// email address contains a domain that is just a TLD with no SLD, e.g. foo@WIN-bar
	Domain string `json:"domain,omitempty"`

	// Interpreted punycode if the domain starts with xn--. For example, if 'domain' is
	// 'xn--ublimesecurity-4xc.com' then 'punycode' is śublimesecurity.com
	Punycode *string `json:"punycode,omitempty"`

	// The root domain, including the TLD
	RootDomain *string `json:"root_domain,omitempty"`

	// Second-level domain, e.g. 'windows' for the domain 'windows.net'
	SLD *string `json:"sld,omitempty"`

	// Subdomain, e.g. 'drive' for the domain 'drive.google.com'
	Subdomain *string `json:"subdomain,omitempty"`

	// The domain's top-level domain. E.g. the TLD of google.com is 'com'
	TLD *string `json:"tld,omitempty"`

	// Whether the domain is valid
	Valid *bool `json:"valid,omitempty"`
}

// EmailAddress email address object
type EmailAddress struct {
	Domain *Domain `json:"domain,omitempty"`

	// Full email address
	Email *string `json:"email,omitempty"`

	// Local-part, i.e. before the @
	LocalPart *string `json:"local_part,omitempty"`
}

// External cloud API provider or other external source metadata
type External struct {

	// The created time of the message as provided by the cloud API (G Suite or Office 365) or
	// other external source. This is typically the time the external source received the
	// message
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// The message ID as provided by the cloud API (G Suite or Office 365) or other external
	// source
	MessageID *string `json:"message_id,omitempty"`

	// whether the message was sent or received
	RouteType *ExternalRouteType `json:"route_type,omitempty"`

	// The upstream mail gateway determined the message to be spam. For cloud API providers,
	// this will be the same as spam_folder. For other implementation methods like transport
	// rules, this will be determined by message header values (e.g. X-SPAM) if supported
	Spam *bool `json:"spam,omitempty"`

	// The message arrived in the user's spam folder. This only applies to cloud APIs (G Suite
	// or Office 365)
	SpamFolder *bool `json:"spam_folder,omitempty"`

	// The thread/conversation's unique ID as provided by the cloud API (G Suite or Office 365)
	ThreadID *string `json:"thread_id,omitempty"`
}

// Headers the message headers
type Headers struct {
	AuthSummary *AuthSummary `json:"auth_summary,omitempty"`

	// Date the email was sent in UTC.
	Date *time.Time `json:"date,omitempty"`

	// UTC timezone offset of the sender
	DateOriginalOffset *string       `json:"date_original_offset,omitempty"`
	DeliveredTo        *EmailAddress `json:"delivered_to,omitempty"`

	// All domains found in the Received headers
	Domains []*Domain `json:"domains,omitempty"`
	From    *Mailbox  `json:"from,omitempty"`

	// List of hops the message took from Sender to Recipient
	Hops []*Hop `json:"hops,omitempty"`

	// In-Reply-To header value which identifies its parent message if exists
	InReplyTo *string `json:"in_reply_to,omitempty"`

	// All IP addresses found in the Received headers
	IPs []*IP `json:"ips,omitempty"`

	// X-Mailer or User-Agent extracted from headers
	Mailer *string `json:"mailer,omitempty"`

	// Message-ID extracted from the header
	MessageID *string `json:"message_id,omitempty"`

	// The Message-IDs of the other messages within this chain
	References []string `json:"references,omitempty"`

	// Where replies should be delivered to
	ReplyTo              []*Mailbox        `json:"reply_to,omitempty"`
	ReturnPath           *EmailAddress     `json:"return_path,omitempty"`
	SensitivityLabel     *SensitivityLabel `json:"sensitivity_label,omitempty"`
	XAuthenticatedDomain *Domain           `json:"x_authenticated_domain,omitempty"`
	XAuthenticatedSender *EmailAddress     `json:"x_authenticated_sender,omitempty"`
	XClientIP            *IP               `json:"x_client_ip,omitempty"`
	XOriginatingIP       *IP               `json:"x_originating_ip,omitempty"`

	// X-SecureServer-Acct header, which represents a unique identifier associated with the
	// sender's email account on a secure server and can be used to trace the email back to a
	// specific account or user.
	XSecureServerAccount *string       `json:"x_secure_server_account,omitempty"`
	XSender              *EmailAddress `json:"x_sender,omitempty"`
}

// Hop is the Mdm_serviceHop component of the Message Data Model.
type Hop struct {
	AuthenticationResults *AuthResults `json:"authentication_results,omitempty"`

	// List of all raw header fields contained within this hop
	Fields []*HopField `json:"fields,omitempty"`

	// Index indicates the order in which a hop occurred from sender to recipient
	Index       int64      `json:"index,omitempty"`
	Received    *Received  `json:"received,omitempty"`
	ReceivedSPF *SPF       `json:"received_spf,omitempty"`
	Signature   *Signature `json:"signature,omitempty"`
}

// HopField is the Mdm_serviceHopField component of the Message Data Model.
type HopField struct {

	// The name of the field
	Name string `json:"name,omitempty"`

	// This field's position along the entire list of header fields
	Position int64 `json:"position,omitempty"`

	// The value contained within the field
	Value *string `json:"value,omitempty"`
}

// IP x-Originating-IP header, which identifies the originating IP address of the sender
// client
type IP struct {

	// The IP in canonical form
	IP          string         `json:"ip,omitempty"`
	Translation *IPTranslation `json:"translation,omitempty"`

	// The version of IP (i.e., 4 or 6), null for backward compatibility.
	Version *int64 `json:"version,omitempty"`
}

// IPTranslation is the Mdm_serviceIPTranslation component of the Message Data Model.
type IPTranslation struct {

	// The radix/form encodings detected on a non-standard IPv4 host that was decoded into 'ip'
	Encoders []IPTranslationEncoders `json:"encoders,omitempty"`

	// The IP in its original form before any translation occurred
	Original *string `json:"original,omitempty"`

	// Whether 'Original' is IPv4-mapped-IPv6
	V4ToV6 *bool `json:"v4_to_v6,omitempty"`
}

// Link is the Mdm_serviceLink component of the Message Data Model.
type Link struct {

	// The text of a hyperlink, if it's not a URL
	DisplayText *string `json:"display_text,omitempty"`
	DisplayURL  *URL    `json:"display_url,omitempty"`
	HrefURL     *URL    `json:"href_url,omitempty"`

	// Whether the display URL and href URL root domains are mismatched (i.e.
	// .href_url.domain.root_domain != .display_url.domain.root_domain, where both are not
	// null and valid domains)
	Mismatched *bool `json:"mismatched,omitempty"`

	// The parser that was used to derived the link
	Parser *LinkParser `json:"parser,omitempty"`

	// Whether the link is visible to a human when previewing an email or page
	Visible *bool `json:"visible,omitempty"`
}

// Mailbox organizer mailbox with email and display name
type Mailbox struct {

	// Display name
	DisplayName *string       `json:"display_name,omitempty"`
	Email       *EmailAddress `json:"email,omitempty"`
}

// MailboxExtended the mailbox where the message was found
type MailboxExtended struct {

	// Display name
	DisplayName *string       `json:"display_name,omitempty"`
	Email       *EmailAddress `json:"email,omitempty"`

	// First name (given name) of the mailbox owner
	FirstName *string `json:"first_name,omitempty"`

	// Last name (surname) of the mailbox owner
	LastName *string `json:"last_name,omitempty"`
}

// MessageDataModel full data model of the message
type MessageDataModel struct {

	// Non-fatal errors while parsing MDM
	Errors []map[string]string `json:"_errors,omitempty"`
	Meta   *Metadata           `json:"_meta,omitempty"`

	// Attachments
	Attachments []*Attachment    `json:"attachments,omitempty"`
	Body        *Body            `json:"body,omitempty"`
	External    *External        `json:"external,omitempty"`
	Headers     *Headers         `json:"headers,omitempty"`
	Mailbox     *MailboxExtended `json:"mailbox,omitempty"`
	Recipients  *Recipients      `json:"recipients,omitempty"`
	Sender      *SenderMailbox   `json:"sender,omitempty"`
	Subject     *Subject         `json:"subject,omitempty"`
	Type        *MessageType     `json:"type,omitempty"`
}

// MessageType override on message types, defined from the perspective of your organization
type MessageType struct {

	// Message was sent from someone outside your organization, to *at least one* recipient
	// inside your organization
	Inbound *bool `json:"inbound,omitempty"`

	// Message was sent from someone inside your organization, to *at least one* recipient
	// inside your organization. Messages *must be authenticated* by either SPF or DKIM to be
	// treated as internal.
	Internal *bool `json:"internal,omitempty"`

	// Message was sent from someone inside your organization, to *at least one* recipient
	// outside your organization
	Outbound *bool `json:"outbound,omitempty"`
}

// Metadata metadata
type Metadata struct {

	// A deterministic ID, generated from metadata such as Attachments, Body, Subject, Sender
	// and is used to group similar messages/campaigns together
	CanonicalID string `json:"canonical_id,omitempty"`

	// Creation time of the data model
	CreatedAt time.Time `json:"created_at,omitempty"`

	// Effective time of the data model, used for evaluation against lists and historical
	// functions such as sender profiles or whois.
	EffectiveAt *time.Time `json:"effective_at,omitempty"`

	// Message ID
	ID *string `json:"id,omitempty"`
}

// Plain the body part containing content-type text/plain
type Plain struct {

	// charset of the text/[subtype]
	Charset *string `json:"charset,omitempty"`

	// Content-Transfer-Encoding of the text/[subtype]
	ContentTransferEncoding *string `json:"content_transfer_encoding,omitempty"`

	// All links found in the plain part of the body of the message
	Links []*Link `json:"links,omitempty"`

	// Decoded raw content of a body text type (text/[subtype] section)
	Raw *string `json:"raw,omitempty"`
}

// PreviousThread is the Mdm_servicePreviousThread component of the Message Data Model.
type PreviousThread struct {

	// All warning banners found in the body of the message.
	Banners []*Banner `json:"banners,omitempty"`

	// Date extracted from thread preamble
	Date *time.Time `json:"date,omitempty"`

	// The index of the thread among all threads, sorted from most recent to oldest
	Index *int64 `json:"index,omitempty"`

	// All links found in the given thread, unique by the target and display text/url.
	Links []*Link `json:"links,omitempty"`

	// The preamble text from the thread, typically the headers of a reply or forward. Things
	// like From, Sent, Subject, saved as one big multiline string. This doesn't include
	// banners.
	Preamble   *string           `json:"preamble,omitempty"`
	Recipients *ThreadRecipients `json:"recipients,omitempty"`
	Sender     *Mailbox          `json:"sender,omitempty"`
	Subject    *Subject          `json:"subject,omitempty"`

	// The text content from the latest reply/forward in a message thread. This typically
	// excludes content from forwarded messages and warning banners.
	Text *string `json:"text,omitempty"`
}

// Received details of the Received field
type Received struct {
	Additional *ReceivedAdditional `json:"additional,omitempty"`
	ID         *ReceivedID         `json:"id,omitempty"`
	Link       *ReceivedVia        `json:"link,omitempty"`
	Mailbox    *ReceivedFor        `json:"mailbox,omitempty"`
	Protocol   *ReceivedWith       `json:"protocol,omitempty"`
	Server     *ReceivedBy         `json:"server,omitempty"`
	Source     *ReceivedFrom       `json:"source,omitempty"`

	// Time parsed from the Received header
	Time *time.Time `json:"time,omitempty"`

	// Timezone offset parsed from the Received header
	ZoneOffset *string `json:"zone_offset,omitempty"`
}

// ReceivedAdditional the remaining additional clauses of the Received header
type ReceivedAdditional struct {

	// The raw string for remaining additional clauses, such as transport information
	Raw *string `json:"raw,omitempty"`
}

// ReceivedBy the 'by' section of the Received header, denoting the current server
type ReceivedBy struct {

	// The raw string of 'by' section
	Raw *string `json:"raw,omitempty"`
}

// ReceivedFor the 'for' section of the Received header, denoting the destination mailbox
type ReceivedFor struct {

	// The raw string of 'for' section
	Raw *string `json:"raw,omitempty"`
}

// ReceivedFrom the 'from' section of the Received header, relating to a server in a prior hop
type ReceivedFrom struct {

	// The raw string of 'from' section
	Raw *string `json:"raw,omitempty"`
}

// ReceivedID the 'id' section of the Received header
type ReceivedID struct {

	// The raw string of 'id' section
	Raw *string `json:"raw,omitempty"`
}

// ReceivedVia the 'via' section of the Received header, denoting transport
type ReceivedVia struct {

	// The raw string of 'via' section
	Raw *string `json:"raw,omitempty"`
}

// ReceivedWith the 'with' section of the Received header, denoting the protocol used
type ReceivedWith struct {

	// The raw string of 'with' section
	Raw *string `json:"raw,omitempty"`
}

// Recipients recipient objects
type Recipients struct {

	// List of 'bcc' Mailbox objects
	BCC []*Mailbox `json:"bcc,omitempty"`

	// List of 'cc' Mailbox objects
	CC []*Mailbox `json:"cc,omitempty"`

	// List of 'to' Mailbox objects
	To []*Mailbox `json:"to,omitempty"`
}

// RewriteDetails information about an original URL that was unfurled from rewrite detection
type RewriteDetails struct {

	// List of detected URL rewrite encoders while unraveling the URL
	Encoders []RewriteDetailsEncoders `json:"encoders,omitempty"`

	// Original URL without any unraveling URL rewrites
	Original string `json:"original,omitempty"`
}

// SPF details of the Sender Policy Framework check. Supported fields include 'Received-SPF'
// and 'X-Received-SPF'
type SPF struct {
	ClientIP *IP `json:"client_ip,omitempty"`

	// Verbose description of the SPF verdict
	Description *string `json:"description,omitempty"`

	// Email or domain of the designating body
	Designator *string `json:"designator,omitempty"`
	Helo       *Domain `json:"helo,omitempty"`
	Server     *Domain `json:"server,omitempty"`

	// Verdict of the SPF
	Verdict *string `json:"verdict,omitempty"`
}

// SPFSummary summary of the SPF check
type SPFSummary struct {
	Details *SPF `json:"details,omitempty"`

	// Whether the SPF check errored
	Error *bool `json:"error,omitempty"`

	// Whether the SPF check passed
	Pass *bool `json:"pass,omitempty"`

	// The lowest hop at which the SPF check was made
	ReceivedHop *int64 `json:"received_hop,omitempty"`
}

// SenderMailbox sender object
type SenderMailbox struct {

	// Decoders used to parse the email sender info, if any
	Decoders []SenderMailboxDecoders `json:"decoders,omitempty"`

	// Display name
	DisplayName *string       `json:"display_name,omitempty"`
	Email       *EmailAddress `json:"email,omitempty"`
}

// SensitivityLabel INTERNAL
type SensitivityLabel struct {

	// Provider-defined sensitivity label ID
	ID *string `json:"id,omitempty"`

	// Label name from provider metadata; not necessarily the display name
	Name *string `json:"name,omitempty"`

	// Provider that defined the sensitivity label
	Provider *string `json:"provider,omitempty"`

	// External provider account that owns the label, such as a Microsoft Entra tenant ID
	ProviderAccountID *string `json:"provider_account_id,omitempty"`
}

// Signature details of a message signature. Supported fields include 'DKIM-Signature',
// 'DomainKey-Signature', 'X-Google-DKIM-Signature' and 'ARC-Message-Signature'
type Signature struct {

	// Signing algorithm
	Algorithm *string `json:"algorithm,omitempty"`

	// Body Hash
	BodyHash *string `json:"body_hash,omitempty"`

	// Domain identified in the DKIM signature if any. This is the domain that's queried for
	// the public key.
	Domain *string `json:"domain,omitempty"`

	// Header fields signed by the algorithm
	Headers *string `json:"headers,omitempty"`

	// Instance number of this signature (if ARC)
	Instance *string `json:"instance,omitempty"`

	// Selector
	Selector *string `json:"selector,omitempty"`

	// Signature of headers and body
	Signature *string `json:"signature,omitempty"`

	// The type of signature, derived from the field name
	Type *string `json:"type,omitempty"`

	// Version
	Version *string `json:"version,omitempty"`
}

// Subject subject object
type Subject struct {

	// Subject of the email with tags and reply/forward indicators removed
	Base *string `json:"base,omitempty"`

	// Indicates if the subject of the email is an automatic reply
	IsAutoReply *bool `json:"is_auto_reply,omitempty"`

	// Indicates if the subject of the email is a forward
	IsForward *bool `json:"is_forward,omitempty"`

	// Indicates if the subject of the email is a reply
	IsReply *bool `json:"is_reply,omitempty"`

	// Subject of the email
	Subject *string `json:"subject,omitempty"`

	// Leading tags extracted from the subject, e.g. [External] or (Warning)
	Tags []string `json:"tags,omitempty"`

	// URLs found in the subject
	URLs []*URL `json:"urls,omitempty"`
}

// Thread the current text thread of the message
type Thread struct {

	// All warning banners found in the body of the message.
	Banners []*Banner `json:"banners,omitempty"`

	// All links found in the given thread, unique by the target and display text/url.
	Links []*Link `json:"links,omitempty"`

	// The preamble text from the thread, typically the headers of a reply or forward. Things
	// like From, Sent, Subject, saved as one big multiline string. This doesn't include
	// banners.
	Preamble *string `json:"preamble,omitempty"`

	// The text content from the latest reply/forward in a message thread. This typically
	// excludes content from forwarded messages and warning banners.
	Text *string `json:"text,omitempty"`
}

// ThreadRecipients recipients extracted from thread preamble
type ThreadRecipients struct {

	// List of 'bcc' Mailbox objects
	BCC []*Mailbox `json:"bcc,omitempty"`

	// List of 'cc' Mailbox objects
	CC []*Mailbox `json:"cc,omitempty"`

	// List of 'to' Mailbox objects
	To []*Mailbox `json:"to,omitempty"`
}

// URL URL details when QR code type is url
type URL struct {
	Domain *Domain `json:"domain,omitempty"`

	// Fragment identifier; the text following the # in the URL (also called the anchor tag)
	Fragment *string `json:"fragment,omitempty"`
	IP       *IP     `json:"ip,omitempty"`

	// The password specified before the domain name
	Password *string `json:"password,omitempty"`

	// Everything after the TLD and before the query parameters
	Path *string `json:"path,omitempty"`

	// The port used for the URL. If no explicit port is set, the port will be inferred from
	// the protocol
	Port *int64 `json:"port,omitempty"`

	// The full query parameters of the URL
	QueryParams *string `json:"query_params,omitempty"`

	// The decoded query parameters of the URL
	QueryParamsDecoded map[string][]string `json:"query_params_decoded,omitempty"`
	Rewrite            *RewriteDetails     `json:"rewrite,omitempty"`

	// Protocol for the URL request, e.g. http
	Scheme *string `json:"scheme,omitempty"`

	// Full URL
	URL string `json:"url,omitempty"`

	// The username specified before the domain name of the URL
	Username *string `json:"username,omitempty"`
}
