// Code generated by tygo. DO NOT EDIT.
// SPDX-License-Identifier: AGPL-3.0-only
//
// Code generated by tygo from the Go wire types. DO NOT EDIT.

//////////
// source: api.go

/**
 * Bootstrap is what the console needs before it can draw anything: who is signed in,
 * what they may do, and the queue depths the navigation shows.
 */
export interface Bootstrap {
  user: WhoAmI;
  counts: { [key: string]: number /* int */};
  read_only: boolean;
  sso: boolean;
  queues: Queue[];
}
/**
 * Queue is one triage tab.
 */
export interface Queue {
  key: string;
  label: string;
  hint: string;
}
/**
 * TriagePage is one queue's worth of mail.
 */
export interface TriagePage {
  messages: Message[];
  counts: { [key: string]: number /* int */};
  state: string;
  window: string;
  total: number /* int */;
}
/**
 * MessagePage is the detail view: the engine's analysis plus what the console adds.
 */
export interface MessagePage {
  id: string;
  detail?: MessageDetail;
  verdict: string;
  /**
   * Screenshot is the URL the Rendered tab loads. A stored message has an endpoint
   * to fetch its picture from; a transient analysis carries one inline instead.
   */
  screenshot?: string;
  /**
   * Insights arrive as one list and are shown as three, because an analyst reads
   * them in that order: who sent it, what is known about them, what is in it.
   */
  identity: Insight[];
  reputation: Insight[];
  content: Insight[];
  summary: { [key: string]: any};
  mdm: any;
  states: Queue[];
}

//////////
// source: auth.go

/**
 * Session is what the cookie resolves to.
 */
export interface Session {
  Token: string;
  User: WhoAmI;
}
/**
 * WhoAmI is the engine's view of the caller.
 */
export interface WhoAmI {
  user_id: string;
  email: string;
  name: string;
  tenant_id: string;
  role: string;
}
/**
 * Auth holds the sign-in configuration.
 */
export interface Auth {
  /**
   * Engine is used for local login and for whoami.
   */
  Engine?: EngineClient;
  /**
   * ServiceToken is an admin API token. It is needed for exactly one thing: turning
   * verified OIDC claims into an engine session, which is a privileged operation
   * because it mints a session for whoever it is told about.
   */
  ServiceToken: string;
  /**
   * Secure marks cookies Secure. On by default; -insecure-cookies turns it off for
   * plain-HTTP local development, and says so loudly.
   */
  Secure: boolean;
  /**
   * DefaultRole is what a first-time SSO user gets. viewer, because an identity
   * provider vouching that someone works here is not the same as deciding they
   * should be able to quarantine mail.
   */
  DefaultRole: string;
}

//////////
// source: client.go

/**
 * EngineClient is the dashboard's only dependency: the engine's public HTTP API.
 * No database handle and no shared Go types. The constraint is deliberate — it keeps
 * the API exercised by a real consumer rather than only by its own tests, and it means
 * anything this UI can do, a script can do too.
 */
export interface EngineClient {
  Base: string;
  Tenant: string;
  HTTP?: any /* http.Client */;
}
/**
 * Message is one row of the triage list.
 */
export interface Message {
  message_id: string;
  received_at: string;
  sender: string;
  subject: string;
  direction: string;
  verdict: string;
  matched: string[];
  missing: string[];
  last_action: string;
  triage_state: string;
}
export interface Insights {
  by_day: DayCount[];
  top_rules: NameCount[];
  top_senders: NameCount[];
  missing_capabilities: NameCount[];
  totals: { [key: string]: number /* int64 */};
}
export interface DayCount {
  day: string;
  malicious: number /* int64 */;
  indeterminate: number /* int64 */;
  clean: number /* int64 */;
}
export interface NameCount {
  name: string;
  count: number /* int64 */;
}
export interface Rule {
  id: string;
  name: string;
  type: string;
  severity: string;
  needs: string[];
  lists: string[];
  source: string;
}
export interface Action {
  action: string;
  reason: string;
  actor: string;
  at: string;
  message_id: string;
}
/**
 * Inference is the model service's execution provider, mirroring ml.Inference.
 */
export interface Inference {
  /**
   * Provider is what it is using: "cpu", "migraphx", "cuda", "tensorrt".
   */
  provider: string;
  /**
   * Tried is what was offered to the runtime. More than one entry with a cpu
   * provider means GPU providers were offered and refused — which is a
   * deployment running without the accelerator someone intended it to have,
   * rather than one that never had a GPU.
   */
  tried?: string[];
}
export interface Capabilities {
  rules_loaded: number /* int */;
  capabilities_used: string[];
  lists_referenced: string[];
  providers_attached: string[];
  /**
   * Health is whether each capability actually answers, probed by the engine
   * with a real call. ProvidersAttached above only ever meant a client was
   * constructed with an address — which is how an unreachable Strelka went
   * unnoticed while a fifth of the rule set silently reported indeterminate.
   */
  capability_health: CapabilityState[];
  capabilities_down: number /* int */;
  rules_unanswerable: number /* int */;
  /**
   * Inference is which execution provider the model service ended up on.
   * Carried to the console because the console is where somebody notices that
   * rules are going unanswered, and a CPU fallback is the likeliest reason. The
   * classifier is 0.3s on a GPU and 8s on a CPU alone, and under real concurrency
   * it was measured at 82s against the engine's 120s budget — at which point 358
   * rules report indeterminate and nothing on the page says why.
   */
  inference?: Inference;
}
/**
 * CapabilityState is whether one enrichment capability answered a real call.
 */
export interface CapabilityState {
  capability: string;
  ok: boolean;
  detail: string;
  rules: number /* int */;
  took_ms: number /* int64 */;
}
export interface HuntJob {
  id: string;
  source: string;
  state: string;
  messages_scanned: number /* int64 */;
  messages_matched: number /* int64 */;
  error: string;
  results: {
    message_id: string;
  }[];
  success?: boolean;
  diagnostics: string;
  /**
   * Undecided is how many messages the expression could not be resolved against,
   * because the evidence it wanted was never kept. Carried through to the console
   * rather than dropped: folding it into "did not match" would turn "we never
   * checked" into "nothing found", which is the one answer a hunt must not give
   * silently.
   */
  messages_undecided: number /* int64 */;
  /**
   * Missing names those capabilities and how often, so a thin result says whether
   * the mail was clean or the evidence was not there.
   */
  missing_evidence: { [key: string]: number /* int */};
}
/**
 * Backtest is what a proposed rule would have done over stored mail.
 */
export interface Backtest {
  id: string;
  rule: string;
  rule_name: string;
  state: string;
  error: string;
  messages_scanned: number /* int64 */;
  messages_matched: number /* int64 */;
  messages_undecided: number /* int64 */;
  missing_evidence: { [key: string]: number /* int */};
  reviewed: number /* int64 */;
  benign: number /* int64 */;
  confirmed: number /* int64 */;
  /**
   * PrecisionKnown says whether enough of the matches had already been judged for
   * Precision to mean anything. The console must not show a figure without it: a
   * rule with two reviews and both benign is unmeasured, not bad.
   */
  precision_known: boolean;
  precision: number /* float64 */;
  results: BacktestHit[];
  diagnostics: string;
}
/**
 * BacktestHit is one message a proposed rule would have fired on.
 */
export interface BacktestHit {
  message_id: string;
  received_at: string;
  subject: string;
  sender: string;
  triage: string;
  verdict: string;
}
/**
 * Finding is something learned about a message after it was delivered.
 */
export interface Finding {
  id: string;
  message_id: string;
  kind: string;
  source: string;
  detail: string;
  state: string;
  found_at: string;
  reviewed_by: string;
  reviewed_at?: string;
  subject: string;
  sender: string;
}
/**
 * Findings is the page: the findings themselves, plus what is still being watched.
 */
export interface Findings {
  findings: Finding[];
  open: number /* int */;
  /**
   * LinksWatched is how many links from delivered mail are still scheduled to be
   * looked at again. Shown because an empty findings list means two very different
   * things depending on whether anything is being watched at all.
   */
  links_watched: number /* int */;
  /**
   * Sweeping says whether new detection content and list updates are checked
   * against delivered mail at all, and WindowDays how far back. Same reason: an
   * empty list means "nothing turned up" or "nothing is checking".
   */
  sweeping: boolean;
  window_days: number /* int */;
}
/**
 * Campaign is one attack that arrived many times.
 */
export interface Campaign {
  id: string;
  size: number /* int */;
  subject: string;
  senders: string[];
  link_domains: string[];
  first_seen: string;
  last_seen: string;
  verdicts: { [key: string]: number /* int */};
  triage: { [key: string]: number /* int */};
  messages: CampaignMember[];
}
/**
 * CampaignMember is one message inside a campaign.
 */
export interface CampaignMember {
  message_id: string;
  received_at: string;
  subject: string;
  sender: string;
  verdict: string;
  triage: string;
  link_domains: string[];
}
/**
 * Campaigns is the page.
 */
export interface Campaigns {
  campaigns: Campaign[];
  /**
   * Considered and Grouped are the claim the page makes: "412 messages, 61 of them
   * in 8 campaigns". Without the first number the second says nothing.
   */
  messages_considered: number /* int */;
  messages_grouped: number /* int */;
}
/**
 * EngineError is a refused request, carrying the status the engine gave.
 * The status is kept rather than folded into the message because the console has to
 * tell the cases apart: a 404 for a message that was purged is a normal thing to say
 * plainly, while a 502 means the engine is down and the page should offer a retry.
 * Flattening both to a string made every failure look like the same failure.
 */
export interface EngineError {
  Status: number /* int */;
  Message: string;
}
/**
 * MessageDetail is everything known about one message, re-evaluated on demand.
 * Insight is one evaluated fact about a message: the evidence behind a verdict.
 */
export interface Insight {
  label: string;
  group: string;
  value?: any;
  warn?: boolean;
  unknown?: boolean;
  missing?: string[];
}
/**
 * AuthBadge is one authentication result, in three states rather than two.
 */
export interface AuthBadge {
  name: string;
  state: string;
  detail?: string;
}
/**
 * SenderDetails is what is known about who sent a message.
 */
export interface SenderDetails extends DomainInfo {
  address?: string;
  display_name?: string;
  domain?: string;
  prevalence?: string;
  known: boolean;
  solicited: boolean;
  seen_benign: boolean;
  seen_bad: boolean;
  root_domain?: string;
}
/**
 * DomainInfo is the registry's view of a domain, in the one shape used wherever a
 * domain is shown — the sender panel and the links table both render these fields, and
 * a second shape for the same facts would drift.
 * Known distinguishes "we could not ask" from "the registry answered"; Registered is
 * only meaningful once Known is true. Collapsing the two is how an unreachable registry
 * comes to look like a clean domain.
 */
export interface DomainInfo {
  domain_known: boolean;
  domain_registered: boolean;
  /**
   * LookedUp is the name actually queried, which is the registrable domain rather
   * than the host when those differ.
   */
  looked_up?: string;
  domain_age_days?: number /* int64 */;
  registrar?: string;
  registrant_company?: string;
  registrant_country?: string;
  registrant_email?: string;
  name_servers?: string[];
}
/**
 * MessageSummary is the identifying header block.
 */
export interface MessageSummary {
  subject?: string;
  sender?: string;
  sender_name?: string;
  recipients?: string[];
  reply_to?: string;
  return_path?: string;
  date?: string;
  direction?: string;
  mailer?: string;
  message_id?: string;
  attachments: number /* int */;
  links: number /* int */;
}
/**
 * ContentView is the message body in the forms an analyst needs.
 */
export interface ContentView {
  text?: string;
  html?: string;
  display_text?: string;
  subject?: string;
}
export interface MessageDetail {
  /**
   * Held says the engine has the original bytes, which is what makes quarantine
   * reversible and therefore permitted.
   */
  held: boolean;
  /**
   * Renderable says the message has a body a browser could lay out, so the
   * Rendered tab asks the engine for a screenshot instead of falling back to text.
   */
  renderable: boolean;
  /**
   * Screenshot is a base64 PNG, present only for an analysis of a message that
   * was not stored: there is no endpoint to fetch one from afterwards, so it
   * comes with the answer.
   */
  screenshot?: string;
  /**
   * Transient marks an analysis of a message that was deliberately not recorded.
   * The view hides what cannot be acted on rather than offering broken buttons.
   */
  transient?: boolean;
  /**
   * Disposition is an analyst's recorded judgement, once released.
   */
  disposition?: string;
  signals?: string[];
  insights?: Insight[];
  auth_badges?: AuthBadge[];
  sender: SenderDetails;
  summary: MessageSummary;
  content: ContentView;
  /**
   * AnalysedAt is when the stored analysis was produced, and Recomputed says this
   * page ran the rules again instead of reading it. Shown, because "what the
   * rules say today" and "what they said when it arrived" are different claims.
   */
  analysed_at?: string;
  recomputed?: boolean;
  /**
   * Learned is what this deployment's own model makes of the message, when one
   * has been trained and is better than guessing. Advisory.
   */
  learned?: LearnedScore;
  message_id: string;
  message_data_model: unknown;
  detections: Detection[];
  indeterminate: Detection[];
  excluded: Detection[];
  queries: { [key: string]: any};
  missing: string[];
  authentication: { [key: string]: any};
  links: Link[];
  origin?: Origin;
  attachments: Attachment[];
  headers: { [key: string]: any};
  actions: Action[];
  triage: TriageState;
}
/**
 * Link is one link and what the registry says about where it points.
 * Typed rather than a map, and that is not a style preference: html/template resolves
 * .URL on a map[string]any by looking up the key "URL", finds "url" instead, and renders
 * an empty cell with no error. The count in the heading stays right, so the table looks
 * populated and every row is blank.
 */
export interface Link extends DomainInfo {
  url: string;
  display_text: string;
  domain: string;
  root_domain: string;
  /**
   * TextMismatch marks a link that displays one address and points at another.
   */
  text_mismatch: boolean;
  /**
   * Shortener marks a destination that is itself a redirect, hiding the real one.
   */
  shortener: boolean;
}
/**
 * Origin is the server that actually handed the message over.
 * The address here is the one thing in a message a sender cannot forge — it is where
 * the connection came from — but only when our own infrastructure recorded it.
 * Authenticated says which of those two situations this is, and the page has to show
 * the difference: acting on a header the sender wrote, believing it to be the origin,
 * is a worse mistake than having no origin at all.
 */
export interface Origin {
  ip: string;
  basis: string;
  authenticated: boolean;
  helo: string;
  rdns: string;
  known: boolean;
  allocated: boolean;
  organization: string;
  network: string;
  country: string;
  range_age_days: number /* int64 */;
  abuse_email: string;
  status: string[];
  asn: number /* int64 */;
  asn_organization: string;
  asn_country: string;
}
/**
 * Attachment is one attachment as the message describes it.
 */
export interface Attachment {
  file_name: string;
  extension: string;
  content_type: string;
  size: number /* int64 */;
  md5: string;
  sha256: string;
}
/**
 * Detection is one rule's outcome with enough to explain it.
 */
export interface Detection {
  id: string;
  name: string;
  severity: string;
  description: string;
  tags: string[];
  techniques: string[];
  attack_types: string[];
  missing: string[];
  source: string;
}
export interface TriageState {
  message_id: string;
  state: string;
  assignee: string;
  reviewed_by: string;
  reviewed_at?: string;
  note: string;
}
export interface Coverage {
  loaded: number /* int */;
  fully_answerable: number /* int */;
  blocked: number /* int */;
  capabilities: {
    capability: string;
    rules: number /* int */;
    available: boolean;
  }[];
  providers: string[];
  lists_unavailable: string[];
}
export interface Effectiveness {
  rules: {
    rule: string;
    fired: number /* int64 */;
    confirmed: number /* int64 */;
    benign: number /* int64 */;
    ignored: number /* int64 */;
    unreviewed: number /* int64 */;
  }[];
  dormant: string[];
  dormant_count: number /* int */;
  loaded: number /* int */;
}
export interface User {
  id: string;
  email: string;
  name: string;
  role: string;
  disabled: boolean;
  local: boolean;
  sso: boolean;
  last_login?: string;
}
/**
 * ListConfig is one named list as the settings page shows it.
 */
export interface ListConfig {
  last_refresh?: string;
  name: string;
  source: string;
  url?: string;
  format?: string;
  description?: string;
  last_error?: string;
  refresh_every_seconds: number /* int */;
  entry_count: number /* int64 */;
  includes: number /* int */;
  excludes: number /* int */;
  rules_using: number /* int */;
  enabled: boolean;
  resolvable: boolean;
  has_auth: boolean;
}
export interface ListOverride {
  name: string;
  value: string;
  kind: string;
  note?: string;
  added_by?: string;
  added_at: string;
}
export interface Mailbox {
  last_seen?: string;
  id: string;
  kind: string;
  address: string;
  host?: string;
  username?: string;
  tls_mode?: string;
  folder?: string;
  graph_user?: string;
  last_error?: string;
  messages: number /* int64 */;
  enabled: boolean;
  remediate: boolean;
  has_secret: boolean;
}
export interface OrgConfig {
  domains: string[];
  vips: OrgVIP[];
  display_names: string[];
}
export interface OrgVIP {
  email: string;
  display_name: string;
}
/**
 * Remediation is queued work for a connector: a message to remove from a mailbox, or
 * one to put back.
 */
export interface Remediation {
  id: number /* int64 */;
  message_id: string;
  mailbox_id: string;
  op: string;
  state: string;
  attempts: number /* int */;
  last_error?: string;
  created_at: string;
  done_at?: string;
}
/**
 * GraphDirectoryUser is one account in the Microsoft directory.
 */
export interface GraphDirectoryUser {
  id: string;
  display_name?: string;
  user_principal_name: string;
  /**
   * Always present: the engine only returns accounts that have one.
   */
  mail: string;
  account_enabled: boolean;
  user_type?: string;
  /**
   * Configured says this address is already collected here.
   */
  configured: boolean;
}
/**
 * GraphDirectory is what a walk of the tenant found.
 * The three counts are one sentence and are meaningless apart: "460 accounts, 431 with
 * a mailbox, 412 already collected" tells an administrator where they stand, while any
 * one number alone invites the wrong conclusion.
 */
export interface GraphDirectory {
  users: GraphDirectoryUser[];
  accounts_in_directory: number /* int */;
  with_mailboxes: number /* int */;
  already_configured: number /* int */;
}
/**
 * BulkAdded is the outcome of onboarding an estate.
 */
export interface BulkAdded {
  added: number /* int */;
  skipped: string[];
  enabled: boolean;
  error?: string;
}
/**
 * Contribution is one feature's pull on a learned score.
 */
export interface Contribution {
  feature: string;
  weight: number /* float64 */;
  toward: string;
}
/**
 * LearnedScore is the model's advisory opinion on one message.
 */
export interface LearnedScore {
  score: number /* float64 */;
  agreement: string;
  why?: Contribution[];
  version?: number /* int */;
  advisory: boolean;
}
/**
 * ModelReport is the state of the learned model, for the settings page.
 */
export interface ModelReport {
  trained: boolean;
  useful: boolean;
  version: number /* int */;
  trained_at?: string;
  reviews: number /* int */;
  confirmed: number /* int */;
  dismissed: number /* int */;
  accuracy: number /* float64 */;
  baseline: number /* float64 */;
  top?: Contribution[];
  need_total: number /* int */;
  need_per_side: number /* int */;
}
/**
 * Backfill is one retrospective scan of a mailbox's existing mail.
 */
export interface Backfill {
  id: string;
  mailbox_id: string;
  since: string;
  until: string;
  state: string;
  cursor?: string;
  examined: number /* int64 */;
  ingested: number /* int64 */;
  duplicates: number /* int64 */;
  flagged: number /* int64 */;
  failures: number /* int64 */;
  keep_raw: boolean;
  last_error: string;
  /**
   * When LastError happened. The engine keeps the text sticky so a transient
   * failure leaves a record, which means the text on its own cannot be read as
   * the scan's current condition — see the console, which shows it against the
   * failure count and this time rather than beside the state.
   */
  last_error_at?: string;
  created_by: string;
  created_at: string;
  updated_at: string;
  finished_at?: string;
}
/**
 * GraphApp is the Microsoft 365 application registration.
 * One per deployment: it is an app registration in a directory with permission over
 * the mailboxes in it, so every Microsoft mailbox authenticates through the same
 * one. The client secret is write-only here — the engine will not return it to a
 * browser session, only to a connector's service token.
 */
export interface GraphApp {
  directory_id: string;
  client_id: string;
  /**
   * Cloud is which Microsoft cloud the tenant is in: "" or "public", "usgov"
   * (GCC High), "usgovdod", "china" (21Vianet). It was a pair of connector flags,
   * which meant a sovereign-cloud deployment configured it in a compose file.
   */
  cloud?: string;
  /**
   * NotifyURL is derived by the engine from the deployment's public address
   * and is read-only here — it is shown so an administrator knows what to
   * allow through their proxy, not so they can change it.
   */
  notify_url: string;
  has_secret: boolean;
  updated_at?: string;
  updated_by: string;
}
/**
 * ActionType is something the platform knows how to do.
 */
export interface ActionType {
  type: string;
  label: string;
  detail: string;
  destructive: boolean;
  needs_custody: boolean;
  touches_mailbox: boolean;
  providers: string[];
  params: ActionParam[];
}
/**
 * ActionParam is one setting an instance of a type needs.
 */
export interface ActionParam {
  name: string;
  label: string;
  detail: string;
  required: boolean;
  placeholder: string;
}
/**
 * ConfiguredAction is a named, configured action that rules are attached to.
 */
export interface ConfiguredAction {
  id: string;
  label: string;
  type: string;
  config: { [key: string]: string};
  enabled: boolean;
  rules: number /* int */;
  updated_at: string;
  updated_by: string;
}
/**
 * RuleFeed is a git repository of detection content.
 * Secret is absent by design: the token is write-only from the console's point of
 * view, exactly as a mailbox credential is. HasSecret is what the page renders.
 */
export interface RuleFeed {
  id: string;
  name: string;
  url: string;
  branch?: string;
  subdir?: string;
  enabled: boolean;
  every_seconds: number /* int */;
  has_secret: boolean;
  last_sync?: string;
  last_commit?: string;
  last_error?: string;
  rule_count: number /* int */;
  created_by?: string;
  created_at: string;
}
