// SPDX-License-Identifier: AGPL-3.0-only

// Command lazaret-ingest is module 6: where mail comes from, and what is done about it.
//
// Four sources, at three different points in a mail system:
//
//	rspamd   inline, before delivery — the only place a verdict can stop a message
//	imap     after delivery, against anything that speaks IMAP
//	graph    Microsoft 365: webhook, falling back to polling
//
// They are not alternatives so much as placements. Rspamd is the strongest, because a
// message that never reaches a mailbox cannot be read; IMAP is the most portable,
// because it needs nothing from the provider but an account; Graph is what a Microsoft
// tenant actually wants, and its two mechanisms differ only in how the news arrives.
//
// # This is the module that makes a verdict mean something
//
// Module 2 records dispositions: quarantine, release, who decided, why. It does not
// perform them. Until this service exists, "quarantine" is a row in an audit table and
// the message is still in the inbox. Here is where the two are joined.
package main

import (
	"runtime/debug"

	"context"
	"errors"
	"flag"
	"fmt"
	"github.com/lazaretemail/lazaret/telemetry"
	"log"
	"os"
	"os/signal"
	"strings"
	"sync"
	"syscall"
	"time"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "lazaret-ingest: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	var (
		engineAddr = flag.String("engine", envOr("LAZARET_ENGINE", "http://localhost:8700"), "lazaret-engine base URL")
		tenant     = flag.String("tenant", envOr("LAZARET_TENANT", "default"), "tenant id")
		// Has to clear the engine's whole worst case, which is three things in a
		// row and not one: up to 30s queued behind its admission limit, then its
		// -analysis-timeout (120s by default), then persisting the result — the
		// custody upload and the two writes, which are deliberately *not* inside
		// the analysis budget, because a message that ran out of time to enrich
		// still has a verdict worth keeping.
		//
		// At three minutes that left about thirty seconds for the last step, and a
		// renderer restarting was enough to spend it: the connector gave up on a
		// message the engine was still working on, threw away two minutes of
		// completed enrichment, and recorded a failure. Timing out here is always
		// the worse outcome, because the engine already bounds itself and will
		// answer — so wait long enough to let it.
		timeout = flag.Duration("timeout", 5*time.Minute,
			"how long to wait for the engine; must exceed its admission wait plus "+
				"-analysis-timeout plus the time to store a result")

		// rspamd
		rspamdAddr   = flag.String("rspamd-addr", envOr("LAZARET_RSPAMD_ADDR", ""), "listen address for the Rspamd Lua plugin, e.g. :8730")
		rspamdSecret = flag.String("rspamd-secret", envOr("LAZARET_RSPAMD_SECRET", ""), "shared secret the plugin sends in the Password header")

		// imap
		imapAddr      = flag.String("imap", envOr("LAZARET_IMAP", ""), "IMAP server, host:port")
		imapUser      = flag.String("imap-user", envOr("LAZARET_IMAP_USER", ""), "IMAP username")
		imapPass      = flag.String("imap-password", envOr("LAZARET_IMAP_PASSWORD", ""), "IMAP password")
		imapMailbox   = flag.String("imap-mailbox", envOr("LAZARET_IMAP_MAILBOX", "INBOX"), "mailbox to watch")
		imapRemediate = flag.Bool("imap-remediate", envOr("LAZARET_IMAP_REMEDIATE", "") != "", "let a malicious verdict remove mail from the mailbox; off observes only")
		imapTLSMode   = flag.String("imap-tls", envOr("LAZARET_IMAP_TLS", "tls"), "tls (implicit), starttls (required), or none")
		imapInsecure  = flag.Bool("imap-insecure", false, "skip certificate verification (lab use only)")
		imapPoll      = flag.Duration("imap-poll", time.Minute, "poll interval when the server has no IDLE")

		// graph
		graphTenant = flag.String("graph-tenant", envOr("LAZARET_GRAPH_TENANT", ""), "Microsoft directory (tenant) id")
		graphClient = flag.String("graph-client", envOr("LAZARET_GRAPH_CLIENT", ""), "application (client) id")
		graphSecret = flag.String("graph-secret", envOr("LAZARET_GRAPH_SECRET", ""), "client secret")
		graphBoxes  = flag.String("graph-mailboxes", envOr("LAZARET_GRAPH_MAILBOXES", ""), "comma-separated user principal names")
		graphNotify = flag.String("graph-notify-url", envOr("LAZARET_GRAPH_NOTIFY_URL", ""), "public HTTPS URL Graph will call; empty means poll only; unmanaged mode only")
		graphAddr   = flag.String("graph-addr", envOr("LAZARET_GRAPH_ADDR", ":8731"), "listen address for Graph notifications")
		graphState  = flag.String("graph-client-state", envOr("LAZARET_GRAPH_CLIENT_STATE", ""), "secret Graph echoes back in every notification; unmanaged mode only, generated by the engine when managed")
		graphPoll   = flag.Duration("graph-poll", 2*time.Minute, "delta poll interval")
		graphWatch  = flag.Duration("graph-watchdog", time.Hour, "silence tolerated before polling starts anyway")
		graphRemed  = flag.Bool("graph-remediate", envOr("LAZARET_GRAPH_REMEDIATE", "") != "", "let a malicious verdict remove mail from the mailbox; off observes only")
		graphBase   = flag.String("graph-base", envOr("LAZARET_GRAPH_BASE", ""), "Graph API host; empty means the public cloud (GCC High: https://graph.microsoft.us)")
		graphLogin  = flag.String("graph-login-base", envOr("LAZARET_GRAPH_LOGIN_BASE", ""), "token host; empty means the public cloud")
	)
	managed := flag.Bool("managed", envOr("LAZARET_MANAGED", "") != "",
		"take the mailbox list from the engine instead of from flags; needs -service-token")
	serviceToken := flag.String("service-token", envOr("LAZARET_SERVICE_TOKEN", ""),
		"engine API token; required with -managed, and used to authenticate every call")
	serviceTokenFile := flag.String("service-token-file", envOr("LAZARET_SERVICE_TOKEN_FILE", ""),
		"read the engine API token from this file instead. The engine provisions one on "+
			"first start, so a stack sharing its state directory needs no token configured "+
			"by hand — and the token never appears in the environment, the process table "+
			"or docker inspect")
	reconcile := flag.Duration("reconcile-every", 1*time.Minute, "how often to re-read the mailbox list")

	flag.Parse()

	// A misconfigured collector must not stop mail being processed: observability
	// is not allowed to take down the thing it observes. Say so loudly and carry on
	// with no-op providers.
	otelShutdown, err := telemetry.Setup(context.Background(), telemetry.Config{
		Service: "lazaret-ingest",
		Version: buildVersion(),
	})
	if err != nil {
		log.Printf("telemetry: disabled, %v", err)
		otelShutdown = func(context.Context) error { return nil }
	}
	defer func() {
		if err := otelShutdown(context.Background()); err != nil {
			log.Printf("telemetry: shutting down: %v", err)
		}
	}()

	// The token file, before anything that reads the token.
	//
	// Ordering matters here and got it wrong once: this used to sit after
	// engine.Token was assigned, so the Engine client kept the empty flag value
	// while the Supervisor — assigned later — got the real one. The mailbox list
	// worked and everything the Engine client did came back 401, which looks like
	// a permissions problem rather than an ordering one.
	//
	// Its own context rather than the signal one, which does not exist yet: the
	// wait is bounded by its own deadline.
	if *serviceTokenFile != "" {
		tok, err := waitForToken(context.Background(), *serviceTokenFile, 2*time.Minute)
		if err != nil {
			return err
		}
		*serviceToken = tok
	}

	engine := NewEngine(*engineAddr, *tenant, *timeout)
	// The connector authenticates to the engine as itself, so its actions are
	// attributed to the token rather than to a person: an audit trail should be able
	// to say "the IMAP connector quarantined this" and not "an analyst did".
	engine.Token = *serviceToken

	var sources []Source

	// Managed mode: the mailboxes come from the engine, where an administrator adds
	// them in the dashboard. The flags below still work and are still the right way
	// to run one mailbox from a shell, but they are no longer the only way, and a new
	// inbox no longer means a redeploy.
	if *managed {
		if *serviceToken == "" {
			return errors.New("-service-token is required with -managed: mailbox credentials are " +
				"readable only by an API token, never by a signed-in session")
		}
		sources = append(sources, &Supervisor{
			Engine: engine, Base: *engineAddr, Token: *serviceToken, Interval: *reconcile,
			GraphTenant: *graphTenant, GraphClient: *graphClient,
			GraphNotify: *graphNotify, GraphAddr: *graphAddr, GraphState: *graphState,
			GraphBase: *graphBase, GraphLogin: *graphLogin,
			IMAPPoll: *imapPoll, GraphPoll: *graphPoll, GraphWatchdog: *graphWatch,
		})
	}

	if *rspamdAddr != "" {
		if *rspamdSecret == "" {
			// Refused rather than warned about. Without it, anyone who can reach the
			// port can submit mail for scoring, which both leaks what the rules do and
			// lets an attacker probe until a message scores clean.
			return errors.New("-rspamd-secret is required when -rspamd-addr is set")
		}
		sources = append(sources, &RspamdSource{
			Addr: *rspamdAddr, Engine: engine, Secret: *rspamdSecret,
		})
	}

	if *imapAddr != "" {
		if *imapUser == "" || *imapPass == "" {
			return errors.New("-imap-user and -imap-password are required with -imap")
		}
		switch *imapTLSMode {
		case "tls", "starttls", "none":
		default:
			return fmt.Errorf("-imap-tls must be tls, starttls or none, not %q", *imapTLSMode)
		}
		sources = append(sources, &IMAPSource{
			Addr: *imapAddr, Username: *imapUser, Password: *imapPass,
			Mailbox: *imapMailbox, Remediate: *imapRemediate,
			TLSMode: *imapTLSMode, Insecure: *imapInsecure, PollInterval: *imapPoll,
			Engine: engine,
		})
	}

	if *graphTenant != "" {
		if *graphClient == "" || *graphSecret == "" {
			return errors.New("-graph-client and -graph-secret are required with -graph-tenant")
		}
		boxes := split(*graphBoxes)
		if len(boxes) == 0 {
			return errors.New("-graph-mailboxes is required: Graph subscriptions are per mailbox")
		}
		if *graphNotify != "" && *graphState == "" {
			return errors.New("-graph-client-state is required when a notification URL is set")
		}
		sources = append(sources, &GraphSource{
			TenantID: *graphTenant, ClientID: *graphClient, ClientSecret: *graphSecret,
			Mailboxes: boxes, NotificationURL: *graphNotify, Addr: *graphAddr,
			ClientState: *graphState, PollInterval: *graphPoll, Watchdog: *graphWatch,
			Remediate: *graphRemed, Engine: engine,
			GraphBase: *graphBase, LoginBase: *graphLogin,
		})
	}

	if len(sources) == 0 {
		return errors.New("no source configured: set -managed, or at least one of -rspamd-addr, -imap or -graph-tenant")
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	// The inline source analyses without recording; everything else ingests.
	//
	// A message Rspamd is about to reject was never delivered, and recording it would
	// build sender history for mail nobody received — the same reasoning that keeps
	// the engine's own analyze endpoint read-only.
	deliver := func(ctx context.Context, msg RawMessage) (*Verdict, error) {
		if msg.Source == "rspamd" {
			return engine.Analyze(ctx, msg)
		}
		v, err := engine.Ingest(ctx, msg)
		if err != nil {
			return nil, err
		}
		if v.Malicious() {
			log.Printf("%s: %s flagged: %s", msg.Source, v.MessageID, describe(v))
		}
		return v, nil
	}

	deliver = instrument(deliver)

	names := make([]string, len(sources))
	for i, s := range sources {
		names[i] = s.Name()
	}
	log.Printf("lazaret-ingest: engine %s, tenant %s, sources %v", *engineAddr, *tenant, names)

	var wg sync.WaitGroup
	errs := make(chan error, len(sources))
	for _, src := range sources {
		wg.Add(1)
		go func(s Source) {
			defer wg.Done()
			if err := s.Run(ctx, deliver); err != nil {
				errs <- fmt.Errorf("%s: %w", s.Name(), err)
			}
		}(src)
	}

	wg.Wait()
	close(errs)
	return <-errs
}

func split(s string) []string {
	var out []string
	for _, p := range strings.Split(s, ",") {
		if p = strings.TrimSpace(p); p != "" {
			out = append(out, p)
		}
	}
	return out
}

func envOr(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

// waitForToken reads the connector's API token, waiting for the engine to write it.
//
// On a fresh stack the engine and the connector start together and the token does
// not exist yet. Waiting is the difference between "bring the stack up" and "bring
// the stack up, watch it fail, bring it up again".
func waitForToken(ctx context.Context, path string, limit time.Duration) (string, error) {
	deadline := time.Now().Add(limit)
	for {
		b, err := os.ReadFile(path)
		if err == nil {
			if tok := strings.TrimSpace(string(b)); tok != "" {
				return tok, nil
			}
		} else if !errors.Is(err, os.ErrNotExist) {
			return "", fmt.Errorf("reading %s: %w", path, err)
		}

		if time.Now().After(deadline) {
			return "", fmt.Errorf("no API token at %s after %s: the engine writes it on "+
				"first start, so check that it started and that both services share the "+
				"state volume", path, limit)
		}
		select {
		case <-ctx.Done():
			return "", ctx.Err()
		case <-time.After(2 * time.Second):
		}
	}
}

// buildVersion reports the revision this binary was built from, for service.version.
func buildVersion() string {
	info, ok := debug.ReadBuildInfo()
	if !ok {
		return ""
	}
	for _, s := range info.Settings {
		if s.Key == "vcs.revision" && len(s.Value) >= 12 {
			return s.Value[:12]
		}
	}
	return info.Main.Version
}
