// SPDX-License-Identifier: Apache-2.0
//
// Not AGPL-3.0 like the rest of this repository, and deliberately so: this file is
// vendored from Strelka and carries Strelka's licence. The Go generated from it is a
// derivative of this, so strelka/strelkapb/*.pb.go is Apache-2.0 too and must not be
// given an AGPL header to make a linter happy.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: strelka.proto

package strelkapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Client        string                 `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Gatekeeper    bool                   `protobuf:"varint,4,opt,name=gatekeeper,proto3" json:"gatekeeper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_strelka_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_strelka_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_strelka_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Request) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *Request) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Request) GetGatekeeper() bool {
	if x != nil {
		return x.Gatekeeper
	}
	return false
}

type Attributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attributes) Reset() {
	*x = Attributes{}
	mi := &file_strelka_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attributes) ProtoMessage() {}

func (x *Attributes) ProtoReflect() protoreflect.Message {
	mi := &file_strelka_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attributes.ProtoReflect.Descriptor instead.
func (*Attributes) Descriptor() ([]byte, []int) {
	return file_strelka_proto_rawDescGZIP(), []int{1}
}

func (x *Attributes) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attributes) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ScanFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // required
	Request       *Request               `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Attributes    *Attributes            `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanFileRequest) Reset() {
	*x = ScanFileRequest{}
	mi := &file_strelka_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanFileRequest) ProtoMessage() {}

func (x *ScanFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strelka_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanFileRequest.ProtoReflect.Descriptor instead.
func (*ScanFileRequest) Descriptor() ([]byte, []int) {
	return file_strelka_proto_rawDescGZIP(), []int{2}
}

func (x *ScanFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ScanFileRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ScanFileRequest) GetAttributes() *Attributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_strelka_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strelka_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_strelka_proto_rawDescGZIP(), []int{3}
}

func (x *ScanResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScanResponse) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

var File_strelka_proto protoreflect.FileDescriptor

const file_strelka_proto_rawDesc = "" +
	"\n" +
	"\rstrelka.proto\"i\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06client\x18\x02 \x01(\tR\x06client\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"gatekeeper\x18\x04 \x01(\bR\n" +
	"gatekeeper\"\x9c\x01\n" +
	"\n" +
	"Attributes\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x125\n" +
	"\bmetadata\x18\x02 \x03(\v2\x19.Attributes.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"v\n" +
	"\x0fScanFileRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\"\n" +
	"\arequest\x18\x02 \x01(\v2\b.RequestR\arequest\x12+\n" +
	"\n" +
	"attributes\x18\x03 \x01(\v2\v.AttributesR\n" +
	"attributes\"4\n" +
	"\fScanResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event2=\n" +
	"\bFrontend\x121\n" +
	"\bScanFile\x12\x10.ScanFileRequest\x1a\r.ScanResponse\"\x00(\x010\x01B3Z1github.com/lazaretemail/lazaret/strelka/strelkapbb\x06proto3"

var (
	file_strelka_proto_rawDescOnce sync.Once
	file_strelka_proto_rawDescData []byte
)

func file_strelka_proto_rawDescGZIP() []byte {
	file_strelka_proto_rawDescOnce.Do(func() {
		file_strelka_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_strelka_proto_rawDesc), len(file_strelka_proto_rawDesc)))
	})
	return file_strelka_proto_rawDescData
}

var file_strelka_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_strelka_proto_goTypes = []any{
	(*Request)(nil),         // 0: Request
	(*Attributes)(nil),      // 1: Attributes
	(*ScanFileRequest)(nil), // 2: ScanFileRequest
	(*ScanResponse)(nil),    // 3: ScanResponse
	nil,                     // 4: Attributes.MetadataEntry
}
var file_strelka_proto_depIdxs = []int32{
	4, // 0: Attributes.metadata:type_name -> Attributes.MetadataEntry
	0, // 1: ScanFileRequest.request:type_name -> Request
	1, // 2: ScanFileRequest.attributes:type_name -> Attributes
	2, // 3: Frontend.ScanFile:input_type -> ScanFileRequest
	3, // 4: Frontend.ScanFile:output_type -> ScanResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_strelka_proto_init() }
func file_strelka_proto_init() {
	if File_strelka_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_strelka_proto_rawDesc), len(file_strelka_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_strelka_proto_goTypes,
		DependencyIndexes: file_strelka_proto_depIdxs,
		MessageInfos:      file_strelka_proto_msgTypes,
	}.Build()
	File_strelka_proto = out.File
	file_strelka_proto_goTypes = nil
	file_strelka_proto_depIdxs = nil
}
