// SPDX-License-Identifier: Apache-2.0
//
// Not AGPL-3.0 like the rest of this repository, and deliberately so: this file is
// vendored from Strelka and carries Strelka's licence. The Go generated from it is a
// derivative of this, so strelka/strelkapb/*.pb.go is Apache-2.0 too and must not be
// given an AGPL header to make a linter happy.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: strelka.proto

package strelkapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Frontend_ScanFile_FullMethodName = "/Frontend/ScanFile"
)

// FrontendClient is the client API for Frontend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FrontendClient interface {
	ScanFile(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ScanFileRequest, ScanResponse], error)
}

type frontendClient struct {
	cc grpc.ClientConnInterface
}

func NewFrontendClient(cc grpc.ClientConnInterface) FrontendClient {
	return &frontendClient{cc}
}

func (c *frontendClient) ScanFile(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ScanFileRequest, ScanResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Frontend_ServiceDesc.Streams[0], Frontend_ScanFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanFileRequest, ScanResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Frontend_ScanFileClient = grpc.BidiStreamingClient[ScanFileRequest, ScanResponse]

// FrontendServer is the server API for Frontend service.
// All implementations must embed UnimplementedFrontendServer
// for forward compatibility.
type FrontendServer interface {
	ScanFile(grpc.BidiStreamingServer[ScanFileRequest, ScanResponse]) error
	mustEmbedUnimplementedFrontendServer()
}

// UnimplementedFrontendServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFrontendServer struct{}

func (UnimplementedFrontendServer) ScanFile(grpc.BidiStreamingServer[ScanFileRequest, ScanResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ScanFile not implemented")
}
func (UnimplementedFrontendServer) mustEmbedUnimplementedFrontendServer() {}
func (UnimplementedFrontendServer) testEmbeddedByValue()                  {}

// UnsafeFrontendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FrontendServer will
// result in compilation errors.
type UnsafeFrontendServer interface {
	mustEmbedUnimplementedFrontendServer()
}

func RegisterFrontendServer(s grpc.ServiceRegistrar, srv FrontendServer) {
	// If the following call pancis, it indicates UnimplementedFrontendServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Frontend_ServiceDesc, srv)
}

func _Frontend_ScanFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FrontendServer).ScanFile(&grpc.GenericServerStream[ScanFileRequest, ScanResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Frontend_ScanFileServer = grpc.BidiStreamingServer[ScanFileRequest, ScanResponse]

// Frontend_ServiceDesc is the grpc.ServiceDesc for Frontend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Frontend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Frontend",
	HandlerType: (*FrontendServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ScanFile",
			Handler:       _Frontend_ScanFile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "strelka.proto",
}
